#!/usr/bin/env bash
# Nexus QA — deploy the docker-compose stack onto the GCP GPU VM.
#
# Runs in Cloud Shell (NOT the VM). It:
#   1. SCPs a small bootstrap script + .env to the VM
#   2. SSHs in and runs the bootstrap (installs Docker, nvidia-container-toolkit,
#      clones your code from a private GitHub repo, brings up docker compose).
#
# Usage:
#   bash deploy_on_vm.sh \
#     <VM_NAME> <ZONE> \
#     <DB_IP> <REDIS_IP> \
#     <GCS_BUCKET> <DB_PASSWORD>
#
# Required env BEFORE running:
#   GH_USER          — GitHub org/user that owns the repo
#                      (default: KVRMtech — the private repo with the
#                      latest D5+D6 fixes shipped 2026-05-19).
#   GH_REPO          — repo name (default: nexusqa)
#   GH_BRANCH        — branch to deploy (default: runpod-snapshot)
#
# Authentication — pick ONE of:
#   GH_PAT           — fine-grained Personal Access Token, read-only on
#                      the repo. The VM clones via HTTPS using this PAT.
#                      Use this when you don't have admin rights to add
#                      a deploy key (the common case for org repos).
#   GH_DEPLOY_KEY    — path to PRIVATE SSH deploy key on Cloud Shell
#                      (NOT your account-level key; create a repo-scoped
#                      SSH deploy key in GitHub Settings → Deploy keys).
#                      Requires admin on the repo. Default:
#                      ~/.ssh/runpod_deploy.
#
# If neither is set, the script falls back to GH_DEPLOY_KEY at the
# default path and exits with a helpful error if missing.
#
# Time: ~30-60 min first run (image builds + Ollama model pull on GPU).

set -eu

VM_NAME="${1:?Usage: deploy_on_vm.sh VM ZONE DB_IP REDIS_IP BUCKET DB_PASS}"
ZONE="${2:?ZONE required}"
DB_IP="${3:?DB_IP required}"
REDIS_IP="${4:?REDIS_IP required}"
GCS_BUCKET="${5:?GCS_BUCKET required}"
DB_PASSWORD="${6:?DB_PASSWORD required}"
PROJECT_ID="${PROJECT_ID:-$(gcloud config get-value project 2>/dev/null)}"
GH_USER="${GH_USER:-KVRMtech}"
GH_REPO="${GH_REPO:-nexusqa}"
GH_BRANCH="${GH_BRANCH:-runpod-snapshot}"
GH_PAT="${GH_PAT:-}"
GH_DEPLOY_KEY="${GH_DEPLOY_KEY:-$HOME/.ssh/runpod_deploy}"

# Pick the auth path. PAT wins when set (most common case — no repo
# admin required). Falls back to SSH deploy key if no PAT.
if [[ -n "$GH_PAT" ]]; then
  AUTH_MODE=pat
elif [[ -f "$GH_DEPLOY_KEY" && -f "${GH_DEPLOY_KEY}.pub" ]]; then
  AUTH_MODE=ssh
else
  echo "ERROR: no GitHub auth configured." >&2
  echo "Set GH_PAT (fine-grained PAT, read-only on the repo) OR" >&2
  echo "provide an SSH deploy key at $GH_DEPLOY_KEY" >&2
  echo "(generate via: ssh-keygen -t ed25519 -f $GH_DEPLOY_KEY -N '')" >&2
  exit 1
fi
echo "Auth mode: $AUTH_MODE"

# ─── Generate the VM-side .env ───────────────────────────────

cat > /tmp/nexus_vm.env <<EOF
# Auto-generated by deploy_on_vm.sh — DO NOT commit.
NEXUS_ENV=production
NEXUS_JWT_SECRET=$(openssl rand -hex 32)
NEXUS_SECRET_KEY=$(openssl rand -hex 32)

# Cloud-managed Postgres (Cloud SQL)
POSTGRES_HOST=${DB_IP}
POSTGRES_PORT=5432
POSTGRES_USER=nexus
POSTGRES_PASSWORD=${DB_PASSWORD}
POSTGRES_DB=nexus

# Cloud-managed Redis (Memorystore)
REDIS_HOST=${REDIS_IP}
REDIS_PORT=6379
REDIS_PASSWORD=
NEXUS_REDIS_URL=redis://${REDIS_IP}:6379

# Production-safe defaults (architect P0 review + this session's findings).
# GPU host: enable OCR on GPU, allow full multimodal enrichment.
ORCHESTRATOR_DEFAULT_PROCESSING_PROFILE=multimodal
EYES_OCR_MAX_WORKERS=2
EYES_OCR_FRAME_TIMEOUT_SECONDS=30
EYES_OCR_GPU=true
EYES_FAST_SKIP_OCR=false
EYES_MULTIMODAL_MAX_SCENES=20
EYES_LLAVA_PER_SCENE_TIMEOUT_S=45
EYES_ANALYZE_SCENES_STAGE_BUDGET_S=600
EYES_LLAVA_CIRCUIT_THRESHOLD=3

# Ollama co-resident on the same VM (GPU).
EYES_OLLAMA_BASE_URL=http://ollama:11434
EYES_OLLAMA_MODEL=llava:7b
EYES_FAST_OLLAMA_MODEL=llava:7b
NEXUS_ALLOW_DEGRADED_MODE=false

# GCS for object storage
NEXUS_STORAGE_BACKEND=gcs
GCS_BUCKET=${GCS_BUCKET}

# Tenant admission + queue saturation thresholds
NEXUS_QUEUE_SATURATION_THRESHOLD=400
EOF

echo "Pushing .env to VM..."
gcloud compute scp /tmp/nexus_vm.env \
  "${VM_NAME}:~/.env" \
  --zone="$ZONE" --project="$PROJECT_ID"

if [[ "$AUTH_MODE" == "ssh" ]]; then
  echo "Pushing SSH deploy key to VM..."
  gcloud compute scp "$GH_DEPLOY_KEY" "${GH_DEPLOY_KEY}.pub" \
    "${VM_NAME}:~/.ssh/" \
    --zone="$ZONE" --project="$PROJECT_ID"
else
  # PAT path: write the token into a tightly-scoped file on the VM,
  # never embedded in the bootstrap script source (heredoc would
  # expand $-vars and the token would land in logs).
  echo "Pushing PAT to VM (read-only file, never echoed)..."
  TMP_PAT=$(mktemp)
  printf '%s\n' "$GH_PAT" > "$TMP_PAT"
  gcloud compute scp "$TMP_PAT" "${VM_NAME}:~/.gh_pat" \
    --zone="$ZONE" --project="$PROJECT_ID"
  rm -f "$TMP_PAT"
fi

# ─── Bootstrap script (runs on the VM) ───────────────────────

REMOTE_BOOTSTRAP="$(cat <<REMOTE_EOF
set -eu
echo "[VM] Hostname: \$(hostname), GPU:"
nvidia-smi | head -10 || echo "GPU not yet ready; driver may still be installing."

echo "[VM] Installing Docker if missing..."
if ! command -v docker >/dev/null 2>&1; then
  curl -fsSL https://get.docker.com | sudo bash
  sudo usermod -aG docker \$USER
fi

echo "[VM] Installing nvidia-container-toolkit..."
if ! command -v nvidia-container-runtime >/dev/null 2>&1; then
  distribution=\$(. /etc/os-release;echo \$ID\$VERSION_ID)
  curl -fsSL https://nvidia.github.io/libnvidia-container/gpgkey \\
    | sudo gpg --dearmor -o /usr/share/keyrings/nvidia-container-toolkit-keyring.gpg
  curl -s -L https://nvidia.github.io/libnvidia-container/\$distribution/libnvidia-container.list \\
    | sed 's#deb https://#deb [signed-by=/usr/share/keyrings/nvidia-container-toolkit-keyring.gpg] https://#g' \\
    | sudo tee /etc/apt/sources.list.d/nvidia-container-toolkit.list
  sudo apt-get update -y
  sudo apt-get install -y nvidia-container-toolkit
  sudo nvidia-ctk runtime configure --runtime=docker
  sudo systemctl restart docker
fi

echo "[VM] Verifying GPU passthrough from Docker..."
sudo docker run --rm --gpus all nvidia/cuda:12.4.0-base-ubuntu22.04 nvidia-smi | head -10

if [ -f ~/.ssh/runpod_deploy ]; then
  echo "[VM] Setting up SSH config for GitHub deploy key..."
  chmod 600 ~/.ssh/runpod_deploy
  chmod 644 ~/.ssh/runpod_deploy.pub
  cat > ~/.ssh/config <<SSH
Host github.com
  HostName github.com
  User git
  IdentityFile ~/.ssh/runpod_deploy
  StrictHostKeyChecking accept-new
SSH
  chmod 600 ~/.ssh/config
  CLONE_URL="git@github.com:${GH_USER}/${GH_REPO}.git"
elif [ -f ~/.gh_pat ]; then
  echo "[VM] Configuring HTTPS clone via PAT..."
  chmod 600 ~/.gh_pat
  _GH_PAT_VAL=\$(cat ~/.gh_pat)
  CLONE_URL="https://oauth2:\${_GH_PAT_VAL}@github.com/${GH_USER}/${GH_REPO}.git"
  # Store as git credential so subsequent pulls don't need it inline
  git config --global credential.helper "store --file=\$HOME/.git-credentials"
  echo "https://oauth2:\${_GH_PAT_VAL}@github.com" > ~/.git-credentials
  chmod 600 ~/.git-credentials
else
  echo "ERROR: no GitHub auth on VM (~/.ssh/runpod_deploy and ~/.gh_pat both missing)"
  exit 1
fi

echo "[VM] Cloning code from GitHub (${GH_USER}/${GH_REPO}@${GH_BRANCH})..."
if [ ! -d ~/nexus ]; then
  git clone --branch "${GH_BRANCH}" "\${CLONE_URL}" ~/nexus
else
  cd ~/nexus
  git fetch origin "${GH_BRANCH}"
  git checkout "${GH_BRANCH}"
  git pull origin "${GH_BRANCH}"
fi
cd ~/nexus/Nexus_power

# .env was scp'd to ~/.env — move it into the working dir.
[ -f ~/.env ] && cp ~/.env .env

echo "[VM] Building base image (5-10 min) then bringing up the stack..."
sudo docker compose build base-image
sudo docker compose up -d

echo "[VM] Pulling LLaVA model into Ollama (5-10 min on GPU)..."
for i in \$(seq 1 30); do
  if sudo docker exec nexus-ollama ollama list >/dev/null 2>&1; then
    sudo docker exec nexus-ollama ollama pull llava:7b
    break
  fi
  sleep 5
done

echo "[VM] Waiting for orchestrator health..."
for i in \$(seq 1 60); do
  if curl -sf http://localhost:8100/health >/dev/null; then
    echo "[VM] Orchestrator healthy."
    break
  fi
  sleep 5
done

echo
echo "[VM] Deployment complete. Public IP: \$(curl -s ifconfig.me)"
echo "[VM]   Orchestrator: http://\$(curl -s ifconfig.me):8100"
echo "[VM]   Client UI:    http://\$(curl -s ifconfig.me):3000"
REMOTE_EOF
)"

echo "Running bootstrap on VM (30-60 min — output streams live)..."
gcloud compute ssh "$VM_NAME" --zone="$ZONE" --project="$PROJECT_ID" \
  -- bash -s <<< "$REMOTE_BOOTSTRAP"

# ─── Get VM public IP for summary ────────────────────────────

VM_IP="$(gcloud compute instances describe "$VM_NAME" --zone="$ZONE" \
  --project="$PROJECT_ID" \
  --format='value(networkInterfaces[0].accessConfigs[0].natIP)')"

cat <<EOF

═══════════════════════════════════════════════════════════════
 Nexus QA — deployment on GCP complete
═══════════════════════════════════════════════════════════════
 Orchestrator   : http://${VM_IP}:8100
 Client UI      : http://${VM_IP}:3000
 SSH            : gcloud compute ssh ${VM_NAME} --zone ${ZONE}

 Smoke test:
   curl http://${VM_IP}:8100/health
═══════════════════════════════════════════════════════════════
EOF
