#!/usr/bin/env bash
# Nexus QA — deploy the docker-compose stack onto the GCP GPU VM.
#
# Runs in two halves:
#   - Part 1 (local / Cloud Shell): SSH into the VM, install Docker +
#     nvidia-container-toolkit, clone the repo, write the .env.
#   - Part 2 (on VM): build images + docker compose up.
#
# Usage:
#   bash deploy_on_vm.sh <VM_IP> <DB_IP> <REDIS_IP> <BUCKET> <DB_PASSWORD>
#
# Time: ~30-60 min for first run (image builds + Ollama model pull).

set -eu

VM_IP="${1:?VM_IP required}"
DB_IP="${2:?DB_IP required}"
REDIS_IP="${3:?REDIS_IP required}"
GCS_BUCKET="${4:?GCS_BUCKET required}"
DB_PASSWORD="${5:?DB_PASSWORD required}"
VM_NAME="${VM_NAME:-nexus-vm}"
ZONE="${ZONE:-us-central1-a}"
PROJECT_ID="${PROJECT_ID:-$(gcloud config get-value project 2>/dev/null)}"
REPO_URL="${REPO_URL:-}"     # set to your git URL if pushing via git
REPO_BRANCH="${REPO_BRANCH:-develop}"

# ─── Generate a .env the VM will use ──────────────────────────

cat > /tmp/nexus_vm.env <<EOF
# Auto-generated by deploy_on_vm.sh — DO NOT commit.
NEXUS_ENV=production
NEXUS_JWT_SECRET=$(openssl rand -hex 32)
NEXUS_SECRET_KEY=$(openssl rand -hex 32)

# Cloud-managed Postgres
POSTGRES_HOST=${DB_IP}
POSTGRES_PORT=5432
POSTGRES_USER=nexus
POSTGRES_PASSWORD=${DB_PASSWORD}
POSTGRES_DB=nexus

# Cloud-managed Redis
REDIS_HOST=${REDIS_IP}
REDIS_PORT=6379
REDIS_PASSWORD=
NEXUS_REDIS_URL=redis://${REDIS_IP}:6379

# Production-safe defaults from the architect P0 review
ORCHESTRATOR_DEFAULT_PROCESSING_PROFILE=fast
EYES_OCR_MAX_WORKERS=2
EYES_OCR_FRAME_TIMEOUT_SECONDS=60
EYES_OCR_GPU=true
EYES_FAST_SKIP_OCR=true
EYES_MULTIMODAL_MAX_SCENES=10
EYES_LLAVA_PER_SCENE_TIMEOUT_S=45
EYES_ANALYZE_SCENES_STAGE_BUDGET_S=480
EYES_LLAVA_CIRCUIT_THRESHOLD=3

# Ollama is co-resident on the same GPU VM
EYES_OLLAMA_BASE_URL=http://ollama:11434
EYES_OLLAMA_MODEL=llava:7b
EYES_FAST_OLLAMA_MODEL=llava:7b
NEXUS_ALLOW_DEGRADED_MODE=false

# GCS bucket (use service-account creds auto-mounted on the VM)
NEXUS_STORAGE_BACKEND=gcs
GCS_BUCKET=${GCS_BUCKET}

# Tenant admission + queue saturation thresholds (defaults are sensible)
NEXUS_QUEUE_SATURATION_THRESHOLD=300
EOF

echo "Wrote /tmp/nexus_vm.env. Copying to VM..."

# ─── Push .env to VM ──────────────────────────────────────────

gcloud compute scp /tmp/nexus_vm.env \
  "${VM_NAME}:~/.env" --zone="$ZONE" --project="$PROJECT_ID"

# ─── Bootstrap the VM ─────────────────────────────────────────

# `gcloud compute ssh` is non-interactive; pipe the bootstrap script in.
gcloud compute ssh "$VM_NAME" --zone="$ZONE" --project="$PROJECT_ID" -- bash -s <<'REMOTE'
set -eu
echo "[VM] Installing Docker (if missing)..."
if ! command -v docker >/dev/null 2>&1; then
  curl -fsSL https://get.docker.com | sudo bash
  sudo usermod -aG docker $USER
fi

echo "[VM] Installing nvidia-container-toolkit..."
if ! command -v nvidia-container-runtime >/dev/null 2>&1; then
  distribution=$(. /etc/os-release;echo $ID$VERSION_ID)
  curl -fsSL https://nvidia.github.io/libnvidia-container/gpgkey \
    | sudo gpg --dearmor -o /usr/share/keyrings/nvidia-container-toolkit-keyring.gpg
  curl -s -L https://nvidia.github.io/libnvidia-container/$distribution/libnvidia-container.list \
    | sed 's#deb https://#deb [signed-by=/usr/share/keyrings/nvidia-container-toolkit-keyring.gpg] https://#g' \
    | sudo tee /etc/apt/sources.list.d/nvidia-container-toolkit.list
  sudo apt-get update -y
  sudo apt-get install -y nvidia-container-toolkit
  sudo nvidia-ctk runtime configure --runtime=docker
  sudo systemctl restart docker
fi

echo "[VM] Verifying GPU access from Docker..."
sudo docker run --rm --gpus all nvidia/cuda:12.2.0-base-ubuntu22.04 nvidia-smi || {
  echo "GPU not accessible from Docker. Driver installation may still be running."
  echo "Wait 2 min and re-run this script."
  exit 1
}

echo "[VM] Cloning Nexus repo (or pulling latest)..."
if [ ! -d "$HOME/nexus" ]; then
  if [ -n "${REPO_URL:-}" ]; then
    git clone --branch "${REPO_BRANCH:-develop}" "${REPO_URL}" "$HOME/nexus"
  else
    echo "REPO_URL not set — you'll need to scp the code yourself."
    echo "From your laptop:"
    echo "  gcloud compute scp --recurse Nexus_power/ ${HOSTNAME}:~/nexus/ --zone=${ZONE}"
    exit 0
  fi
fi

cd "$HOME/nexus"
[ -f ../.env ] && cp ../.env .env

echo "[VM] Pulling Ollama LLaVA model in background (15-20 min)..."
sudo docker run -d --gpus all --name ollama-init \
  -v ollama-data:/root/.ollama \
  ollama/ollama:latest \
  sh -c "ollama serve & sleep 5 && ollama pull llava:7b && tail -f /dev/null" || true

echo "[VM] Bringing up the stack with docker compose..."
sudo docker compose up -d --build

echo "[VM] Waiting for orchestrator health..."
for i in $(seq 1 60); do
  if curl -sf http://localhost:8100/health > /dev/null; then
    echo "Orchestrator healthy."
    break
  fi
  sleep 5
done

echo "[VM] Deployment complete."
echo "Orchestrator: http://$(curl -s ifconfig.me):8100"
echo "Client UI:    http://$(curl -s ifconfig.me):3000"
REMOTE

echo
echo "═════════════════════════════════════════════════════════════"
echo " Deploy step finished. Open:"
echo "   Client UI:    http://${VM_IP}:3000"
echo "   Orchestrator: http://${VM_IP}:8100"
echo "═════════════════════════════════════════════════════════════"
