"""Deterministic ProductionTestCase -> Playwright TypeScript compiler.

Pure string compilation (no LLM, no I/O, no Date/random) — the same case always
produces byte-identical code. Reads only the OBSERVED evidence already stored on
each step.
"""

from __future__ import annotations

import re
from typing import Iterable, Sequence

from .locators import element_locator, js_regex_literal, js_str, url_path

_SLUG_RX = re.compile(r"[^a-z0-9]+")


def _slug(text: str, fallback: str = "test") -> str:
    s = _SLUG_RX.sub("-", (text or "").lower()).strip("-")
    return s or fallback


def _confidence(step) -> str:
    return (getattr(step, "confidence", "") or "").strip().lower()


def _provenance(step) -> str:
    return (getattr(step, "provenance", "") or "").strip().lower()


def _observed(step) -> dict:
    return getattr(step, "observed", None) or {}


def _compile_step(step) -> list[str]:
    """TypeScript lines for one step, prefixed with a provenance comment."""
    observed = _observed(step)
    verb = (observed.get("verb") or "").strip().lower()
    value = observed.get("value", "")
    url = observed.get("url", "")
    label = observed.get("label", "")
    after = (observed.get("after") or "").strip()
    n = getattr(step, "step_number", None)
    action = (getattr(step, "action", "") or "").strip()
    prov = _provenance(step)

    tag = "observed" if prov == "demonstrated" else (prov or "step")
    lines = [f"  // step {n} — {tag}: {action}"]

    # Honest stub: un-observed (inferred) or low-confidence steps are flagged,
    # never invented — they fail toward review, not a fake green.
    if prov == "inferred" or _confidence(step) == "review":
        lines.append("  // TODO(human): not directly observed in the recording — "
                     "confirm the action/locator before relying on this step.")
        lines.append(f"  //   intent: {action}")
        return lines

    if verb == "navigate":
        if action.startswith("Open ") and url:
            lines.append(f"  await page.goto('{js_str(url)}');")
        else:
            path = url_path(url)
            if path:
                lines.append(f"  await expect(page).toHaveURL({js_regex_literal(path)});")
            else:
                lines.append(f"  // observed navigation: {action}")
    elif verb == "assert_required":
        fields = [f.strip() for f in str(label).split(",") if f.strip()]
        for fld in fields:
            lines.append(f"  await expect(page.getByLabel('{js_str(fld)}')).toBeVisible();")
    elif verb == "type":
        loc = element_locator(observed)
        lines.append(f"  await {loc}.fill('{js_str(value)}');")
        # Semantic, step-anchored assertion: the value actually persisted.
        lines.append(f"  await expect({loc}).toHaveValue('{js_str(value)}');")
    elif verb == "select":
        loc = element_locator(observed)
        if (observed.get("kind") or "").strip().lower() == "toggle":
            lines.append(f"  await {loc}.click();")
        else:
            lines.append(f"  await {loc}.selectOption('{js_str(value)}');")
    elif verb == "click":
        loc = element_locator(observed)
        lines.append(f"  await {loc}.click();")
    else:
        lines.append(f"  // (no executable action derived) {action}")

    # The observed outcome is carried as evidence. A locatable assertion for it
    # is synthesized in a later phase; here it is recorded honestly, not faked.
    if after:
        lines.append(f"  // observed outcome: {after}")
    return lines


def compile_case(tc) -> str:
    """Compile one ProductionTestCase to a Playwright .spec.ts file (string)."""
    name = (getattr(tc, "name", None) or "Generated test").strip()
    description = (getattr(tc, "description", None) or "").strip()
    steps = list(getattr(tc, "steps", None) or [])
    high = sum(1 for s in steps if _confidence(s) == "high")
    review = sum(1 for s in steps if _confidence(s) == "review")

    header = [
        "// GENERATED by Nexus Script Factory — deterministic, grounded in a real recording.",
        "// Every locator/assertion is derived from OBSERVED evidence (role + label +",
        "// value + anchor + outcome). No LLM, no inference. Edit freely — you own this code.",
    ]
    if description:
        header.append(f"// {description}")
    header.append(f"// Confidence: {high} solid step(s), {review} need review (see TODO).")

    body: list[str] = []
    for step in steps:
        body.extend(_compile_step(step))
        body.append("")
    if body and body[-1] == "":
        body.pop()

    out: list[str] = []
    out.extend(header)
    out.append("")
    out.append("import { test, expect } from '@playwright/test';")
    out.append("")
    out.append(f"test('{js_str(name)}', async ({{ page }}) => {{")
    out.extend(body)
    out.append("});")
    out.append("")
    return "\n".join(out)


# ─── Minimal runnable scaffold (Phase 1 ships a runnable project; POM/fixtures/
#     data tables / CI presets arrive in Phase 2) ──────────────────────────────

_PACKAGE_JSON = """\
{
  "name": "nexus-generated-e2e",
  "private": true,
  "version": "1.0.0",
  "scripts": {
    "test": "playwright test",
    "report": "playwright show-report"
  },
  "devDependencies": {
    "@playwright/test": "^1.48.0",
    "typescript": "^5.5.0"
  }
}
"""

_PLAYWRIGHT_CONFIG = """\
import { defineConfig, devices } from '@playwright/test';

export default defineConfig({
  testDir: './tests',
  fullyParallel: true,
  forbidOnly: true,
  retries: 0,
  reporter: [['list'], ['html', { open: 'never' }]],
  use: {
    trace: 'on-first-retry',
    screenshot: 'only-on-failure',
  },
  projects: [
    { name: 'chromium', use: { ...devices['Desktop Chrome'] } },
  ],
});
"""

_TSCONFIG = """\
{
  "compilerOptions": {
    "target": "ES2021",
    "module": "CommonJS",
    "moduleResolution": "Node",
    "strict": true,
    "esModuleInterop": true,
    "skipLibCheck": true,
    "types": ["node"]
  }
}
"""


def _readme(case_count: int, high: int, review: int) -> str:
    return (
        "# Nexus-generated Playwright suite\n\n"
        "Deterministically generated from a real, recorded session — grounded in "
        "observed evidence (role + label + value + anchor + outcome), no LLM.\n\n"
        f"- Test specs: {case_count}\n"
        f"- Solid steps: {high}  ·  Steps needing review (TODO): {review}\n\n"
        "## Run\n\n"
        "```bash\nnpm install\nnpx playwright install --with-deps\nnpm test\n```\n\n"
        "You own this code — edit it like any hand-written Playwright suite. Steps "
        "marked `TODO(human)` were not directly observed in the recording; confirm "
        "them before relying on the test.\n"
    )


def compile_project(cases: Iterable) -> dict[str, str]:
    """Compile active cases into a runnable Playwright project (path -> content)."""
    cases = list(cases)
    files: dict[str, str] = {}
    used: dict[str, int] = {}
    high = review = 0
    for tc in cases:
        steps = list(getattr(tc, "steps", None) or [])
        high += sum(1 for s in steps if _confidence(s) == "high")
        review += sum(1 for s in steps if _confidence(s) == "review")
        kind = _slug(getattr(tc, "type", "") or "functional", "functional")
        base = _slug(getattr(tc, "name", "") or "test", "test")
        key = f"tests/{kind}/{base}"
        # de-duplicate filenames deterministically
        if key in used:
            used[key] += 1
            path = f"{key}-{used[key]}.spec.ts"
        else:
            used[key] = 0
            path = f"{key}.spec.ts"
        files[path] = compile_case(tc)

    files["package.json"] = _PACKAGE_JSON
    files["playwright.config.ts"] = _PLAYWRIGHT_CONFIG
    files["tsconfig.json"] = _TSCONFIG
    files["README.md"] = _readme(len(cases), high, review)
    return files
