"""Smoke test for P5 multi-format test exporters.

Builds a realistic ExportContext (no DB, no LLM) and runs each registered
exporter against it. Asserts:
  * every exporter returns a non-empty payload
  * the payload is a valid ZIP
  * the ZIP contains at least one file per app instance
  * Playwright / Cypress files contain selectors + assertions
  * Gherkin uses Given/When/Then keywords
  * JSON parses and contains the expected scenario shape
  * NO stub strings leak through ("Visual Flow Smoke Test", "All transitions succeed")

Run:
    python Nexus_power/platform/api/tests/test_exporters_smoke.py
"""
from __future__ import annotations

import io
import json
import sys
import types
import zipfile
from pathlib import Path

# ── Path setup so `from app...` works ─────────────────────────────────────
_API_ROOT = Path(__file__).resolve().parents[1]
_SDK_ROOT = _API_ROOT.parents[1] / "sdk" / "nexus-sdk"
sys.path.insert(0, str(_API_ROOT))
sys.path.insert(0, str(_SDK_ROOT))


# ── Stub nexus_sdk pieces the imports touch but the exporters don't use ──
# Only `e2e_lifecycle.is_exportable_state` reaches into nexus_sdk.db.models.
# Stub the model module so import-time doesn't drag in the full ORM.
def _make_placeholder(name: str) -> type:
    return type(name, (), {"__init__": lambda self, *a, **kw: None})


_FORBIDDEN_TITLE_STRINGS = (
    "Visual Flow Smoke Test",
    "All transitions succeed",
    "TODO: automate",  # only allowed as a code comment, not a title
)


# ── Realistic mock ExportContext ─────────────────────────────────────────


def build_context():
    from app.services.test_exporters import ExportContext

    controls_by_id = {
        "ctl-signin": {
            "control_id": "ctl-signin",
            "scene_id": "sc-1",
            "element_type": "button",
            "label_text": "Sign In",
            "playwright_selector": "button:has-text('Sign In')",
            "selector_confidence": 0.95,
            "selector_source": "ocr",
            "automation_ready": True,
        },
        "ctl-dob": {
            "control_id": "ctl-dob",
            "scene_id": "sc-2",
            "element_type": "date",
            "label_text": "Date of birth",
            "playwright_selector": "input[name='dob']",
            "selector_confidence": 0.92,
            "selector_source": "ocr",
            "automation_ready": True,
        },
        "ctl-calc": {
            "control_id": "ctl-calc",
            "scene_id": "sc-2",
            "element_type": "button",
            "label_text": "Calculate",
            "playwright_selector": "button:has-text('Calculate')",
            "selector_confidence": 0.94,
            "selector_source": "ocr",
            "automation_ready": True,
        },
    }
    scenes_by_id = {
        "sc-1": {"scene_id": "sc-1", "scene_index": 0, "screen_name": "Login"},
        "sc-2": {"scene_id": "sc-2", "scene_index": 1, "screen_name": "Quote Form"},
        "sc-3": {"scene_id": "sc-3", "scene_index": 2, "screen_name": "Result"},
    }
    edges_by_id = {
        "e-1": {"edge_id": "e-1", "from_scene_id": "sc-1", "to_scene_id": "sc-2"},
        "e-2": {"edge_id": "e-2", "from_scene_id": "sc-2", "to_scene_id": "sc-3"},
    }

    happy_test = {
        "scenario_id": "vs_001",
        "title": "Happy path — sign in and calculate quote",
        "strategy": "happy_path",
        "category": "observed",
        "priority": "P0_critical",
        "rationale": "Generated by happy_path strategy",
        "preconditions": ["User is on Quote Portal", "URL: https://example.com/login"],
        "expected_outcome": "Result screen visible",
        "workflow_steps_covered": [1, 2, 3],
        "risk_areas_addressed": ["action triggering"],
        "data_matrix": [],
        "state": "approved",
        "visual_proven_steps": 3,
        "visual_total_steps": 3,
        "steps": [
            {
                "step_number": 1,
                "action": "Click Sign In",
                "target_element": "button:has-text('Sign In')",
                "input_data": "",
                "expected_output": "Quote Form visible",
                "evidence_scene_id": "sc-1",
                "evidence_control_id": "ctl-signin",
                "evidence_edge_id": "e-1",
                "proof_confidence": 0.94,
            },
            {
                "step_number": 2,
                "action": "Fill Date of birth",
                "target_element": "input[name='dob']",
                "input_data": "1962-03-15",
                "expected_output": "DOB entered",
                "evidence_scene_id": "sc-2",
                "evidence_control_id": "ctl-dob",
                "evidence_edge_id": "",
                "proof_confidence": 0.90,
            },
            {
                "step_number": 3,
                "action": "Click Calculate",
                "target_element": "button:has-text('Calculate')",
                "input_data": "",
                "expected_output": "Premium amount visible",
                "evidence_scene_id": "sc-2",
                "evidence_control_id": "ctl-calc",
                "evidence_edge_id": "e-2",
                "proof_confidence": 0.91,
            },
        ],
    }

    return ExportContext(
        artifact_id="db2435ea-7376-4d61-ad0b-8a1377a9a049",
        tenant_id="tenant-test",
        test_cases=[happy_test],
        controls_by_id=controls_by_id,
        scenes_by_id=scenes_by_id,
        edges_by_id=edges_by_id,
        tc_by_inst={"app-A": [happy_test]},
        inst_name_map={"app-A": "Quote Portal", "unassigned": "App"},
        scenarios_skipped_by_state={"draft": 4},
        total_scenarios_before_filter=5,
    )


# ── Tests ─────────────────────────────────────────────────────────────────


def _assert_no_stubs(text: str, fmt: str) -> None:
    for forbidden in _FORBIDDEN_TITLE_STRINGS:
        if forbidden == "TODO: automate":
            continue  # acceptable as a code-only comment
        assert forbidden not in text, f"{fmt}: stub leaked: {forbidden!r}"


def _read_zip(payload: bytes) -> dict[str, str]:
    files: dict[str, str] = {}
    with zipfile.ZipFile(io.BytesIO(payload)) as zf:
        for name in zf.namelist():
            files[name] = zf.read(name).decode("utf-8")
    return files


def test_playwright_exporter():
    from app.services.test_exporters import PlaywrightExporter
    bundle = PlaywrightExporter(build_context()).render()
    assert bundle.content_type == "application/zip"
    files = _read_zip(bundle.payload)
    assert len(files) == 1, f"expected 1 spec file, got {len(files)}: {list(files)}"
    name, content = next(iter(files.items()))
    assert name.endswith(".spec.ts"), name
    assert "import { test, expect }" in content
    assert "button:has-text('Sign In')" in content
    assert "input[name='dob']" in content
    assert "1962-03-15" in content, "input_data should appear in fill() call"
    assert "// Evidence: scene_id=sc-1" in content
    _assert_no_stubs(content, "playwright")
    print(f"[OK] Playwright: {len(content)} chars, contains real selectors + evidence")


def test_cypress_exporter():
    from app.services.test_exporters import CypressExporter
    bundle = CypressExporter(build_context()).render()
    files = _read_zip(bundle.payload)
    assert len(files) == 1
    content = next(iter(files.values()))
    assert "describe(" in content
    assert "cy.get(" in content
    assert "button:has-text('Sign In')" in content
    assert "1962-03-15" in content
    _assert_no_stubs(content, "cypress")
    print(f"[OK] Cypress: contains describe + cy.get + real selectors")


def test_gherkin_exporter():
    from app.services.test_exporters import GherkinExporter
    bundle = GherkinExporter(build_context()).render()
    files = _read_zip(bundle.payload)
    assert len(files) == 1
    content = next(iter(files.values()))
    assert content.startswith("# App: Quote Portal") or "Feature: Quote Portal" in content
    # Must have at least one Given/When/Then keyword (case-sensitive in Gherkin)
    assert any(kw in content for kw in ("Given ", "When ", "Then ")), content[:200]
    assert "@happy-path" in content
    assert "Evidence: scene=sc-1" in content
    _assert_no_stubs(content, "gherkin")
    print(f"[OK] Gherkin: contains Feature/Scenario + Given/When/Then + evidence")


def test_json_exporter():
    from app.services.test_exporters import JsonExporter
    bundle = JsonExporter(build_context()).render()
    files = _read_zip(bundle.payload)
    assert len(files) == 1
    raw = next(iter(files.values()))
    plan = json.loads(raw)
    assert plan["version"] == "1.0"
    assert plan["artifact_id"].startswith("db2435ea")
    assert len(plan["scenarios"]) == 1
    sc = plan["scenarios"][0]
    assert sc["scenario_id"] == "vs_001"
    assert sc["strategy"] == "happy_path"
    assert len(sc["steps"]) == 3
    step = sc["steps"][0]
    assert step["evidence"]["scene_id"] == "sc-1"
    assert step["evidence"]["control_id"] == "ctl-signin"
    assert step["selector"] == "button:has-text('Sign In')"
    assert step["automation_ready"] is True
    # Summary must reflect filter stats
    assert plan["summary"]["total_scenarios_before_filter"] == 5
    assert plan["summary"]["scenarios_skipped_by_state"]["draft"] == 4
    print(f"[OK] JSON: schema 1.0, all evidence preserved, summary reflects filter")


def test_registry_completeness():
    from app.services.test_exporters import REGISTRY
    assert set(REGISTRY) == {"playwright", "cypress", "gherkin", "json"}, REGISTRY
    print(f"[OK] Registry: {sorted(REGISTRY)}")


if __name__ == "__main__":
    test_registry_completeness()
    test_playwright_exporter()
    test_cypress_exporter()
    test_gherkin_exporter()
    test_json_exporter()
    print("\nAll P5 exporter smoke tests passed.")
