"""Phase R4 — reach formats + dashboard analytics for the Evidence Report.

CSV / JUnit-XML / XLSX / PDF renderings plus the §2.14 analytics.

Two honesty constraints shape this module:

  * **Lossy formats must say so.** JUnit XML has four outcomes; our state
    machine has seven. The mapping is documented in the file itself and the
    richer class is carried in ``<properties>`` so nothing is silently
    flattened. Crucially, an EXECUTION ERROR (our automation) maps to
    ``<error>`` while a DEFECT (the application) maps to ``<failure>`` — a CI
    gate can then tell "our tooling broke" from "your product broke".
  * **No fabricated confidence (D1).** The dashboard reports an
    *evidence-class* distribution (PROVEN / INFERRED / UNVERIFIED), which is
    measured, instead of the "AI confidence distribution" a reader would
    reasonably assume was calibrated.

PDF is generated by a small self-contained writer: no reportlab/weasyprint, so
an air-gapped on-prem install can still produce the auditor's PDF.
"""

from __future__ import annotations

import csv
import io
import zlib
from xml.sax.saxutils import escape as _xml_escape

from .evidence_report import (
    ST_BLOCKED, ST_CANCELLED, ST_COMPLETED_WITH_DEFECTS, ST_DEFECT,
    ST_DEFECT_HALTED, ST_EXEC_ERROR, ST_NEEDS_REVIEW, ST_NOT_EXECUTED,
    ST_PASSED, ST_SKIPPED, TRIPLET_KEYS,
)


def _iter_cases(report: dict):
    for flow in report.get("flows") or []:
        for case in flow.get("cases") or []:
            yield flow, case


# ── §2.14 dashboard analytics ────────────────────────────────────────────────

def build_analytics(report: dict) -> dict:
    """Execution analytics. Every number is a count or an average of stored
    values — nothing is modelled, estimated or inferred."""
    cases = [c for _f, c in _iter_cases(report)]
    executed = [c for c in cases if c.get("executed")]
    steps = [(f, c, s) for f, c in _iter_cases(report) for s in (c.get("steps") or [])]

    n_exec = len(executed) or 0
    passed = sum(1 for c in executed if c.get("status") == ST_PASSED)
    defects = sum(1 for c in executed
                  if c.get("status") in (ST_COMPLETED_WITH_DEFECTS, ST_DEFECT_HALTED))
    errors = sum(1 for c in executed if c.get("status") == ST_EXEC_ERROR)
    blocked = sum(1 for c in executed if c.get("status") == ST_BLOCKED)
    review = sum(1 for c in executed if c.get("status") == ST_NEEDS_REVIEW)

    def rate(n: int) -> float | None:
        return round(100.0 * n / n_exec, 1) if n_exec else None

    durations = [(c.get("duration_ms") or 0, c.get("name") or "") for c in executed]
    longest = max(durations, default=(0, ""))
    step_durs = [((s.get("duration_ms") or 0),
                  f'{c.get("name", "")} · step {s.get("step_number")}')
                 for _f, c, s in steps]
    slowest = max(step_durs, default=(0, ""))

    ev_dist: dict[str, int] = {}
    for _f, _c, s in steps:
        k = s.get("evidence_class") or "UNVERIFIED"
        ev_dist[k] = ev_dist.get(k, 0) + 1

    cause_freq: dict[str, int] = {}
    for d in ((report.get("defects") or {}).get("defects") or []):
        key = f'{d.get("display_status")}:{d.get("cause")}'
        cause_freq[key] = cause_freq.get(key, 0) + int(d.get("occurrence_count") or 0)
    ranked = sorted(cause_freq.items(), key=lambda kv: -kv[1])

    flow_impact = []
    for flow in report.get("flows") or []:
        bad = sum(1 for c in flow.get("cases") or []
                  if c.get("status") in (ST_DEFECT, ST_COMPLETED_WITH_DEFECTS,
                                         ST_DEFECT_HALTED, ST_EXEC_ERROR,
                                         ST_NEEDS_REVIEW))
        if bad:
            flow_impact.append({"flow": flow.get("flow_label"), "impacted_cases": bad,
                                "total_cases": flow.get("case_count")})
    flow_impact.sort(key=lambda x: -x["impacted_cases"])

    return {
        "cases_executed": n_exec,
        "pass_rate_pct": rate(passed),
        "defect_rate_pct": rate(defects),
        "execution_error_rate_pct": rate(errors),
        "blocked_count": blocked,
        "needs_review_count": review,
        "avg_case_duration_ms": (round(sum(d for d, _ in durations) / n_exec)
                                 if n_exec else None),
        "longest_case": {"duration_ms": longest[0], "name": longest[1]},
        "slowest_step": {"duration_ms": slowest[0], "name": slowest[1]},
        "evidence_class_distribution": ev_dist,
        "most_frequent_findings": [{"key": k, "occurrences": v} for k, v in ranked[:10]],
        "top_impacted_flows": flow_impact[:10],
        "honesty_note": (
            "Rates are over EXECUTED cases only; cases that did not run are "
            "reported under coverage, never folded into a pass rate. The "
            "distribution shown is evidence CLASS (measured), not a model "
            "confidence score."
        ),
    }


# ── filters (§2.13) ──────────────────────────────────────────────────────────

def filter_report(report: dict, *, statuses: set[str] | None = None,
                  flow: str | None = None, test_type: str | None = None,
                  search: str | None = None) -> dict:
    """Return a copy of the report narrowed to matching cases.

    Filtering NEVER rewrites the top-level totals — the summary keeps
    describing the whole execution, so a filtered view can't be mistaken for a
    smaller, greener run.
    """
    import copy
    rep = copy.deepcopy(report)
    q = (search or "").strip().lower()
    out_flows = []
    for f in rep.get("flows") or []:
        if flow and str(f.get("flow_key", "")).lower() != flow.strip().lower():
            continue
        kept = []
        for c in f.get("cases") or []:
            if statuses and c.get("status") not in statuses:
                continue
            if test_type and str(c.get("test_type", "")).lower() != test_type.lower():
                continue
            if q:
                hay = " ".join([
                    str(c.get("name", "")), str(c.get("description", "")),
                    " ".join(str(s.get("action", "")) for s in (c.get("steps") or [])),
                    " ".join(str(s.get("actual", "")) for s in (c.get("steps") or [])),
                ]).lower()
                if q not in hay:
                    continue
            kept.append(c)
        if kept:
            f["cases"] = kept
            f["case_count"] = len(kept)
            out_flows.append(f)
    rep["flows"] = out_flows
    rep["filter"] = {
        "statuses": sorted(statuses) if statuses else None, "flow": flow,
        "test_type": test_type, "search": search,
        "matched_cases": sum(len(f["cases"]) for f in out_flows),
        "note": ("Filtered VIEW. The summary totals still describe the whole "
                 "execution, so a filtered report cannot read as a smaller run."),
    }
    return rep


# ── CSV ──────────────────────────────────────────────────────────────────────

def to_csv(report: dict) -> str:
    """One row per executed step — the format analysts pivot on."""
    buf = io.StringIO()
    w = csv.writer(buf, lineterminator="\n")
    w.writerow(["flow", "test_case_id", "case_name", "test_type", "priority",
                "case_status", "step_number", "step_status", "status_badge",
                "action", "target", "expected", "actual", "evidence_class",
                "attribution_category", "attribution_cause", "ai_suggested",
                "duration_ms", "screenshot_url", "trace_url"])
    for flow, case in _iter_cases(report):
        if not (case.get("steps") or []):
            w.writerow([flow.get("flow_label"), case.get("test_case_id"),
                        case.get("name"), case.get("test_type"), case.get("priority"),
                        case.get("status"), "", ST_NOT_EXECUTED, "",
                        case.get("not_executed_reason", ""), "", "", "", "", "", "",
                        "", 0, "", ""])
            continue
        for s in case["steps"]:
            an = s.get("analysis") or {}
            ev = s.get("evidence") or {}
            w.writerow([flow.get("flow_label"), case.get("test_case_id"),
                        case.get("name"), case.get("test_type"), case.get("priority"),
                        case.get("status"), s.get("step_number"), s.get("status"),
                        s.get("status_badge"), s.get("action"), s.get("target"),
                        s.get("expected"), s.get("actual"), s.get("evidence_class"),
                        an.get("category", ""), an.get("cause", ""),
                        an.get("suggested", ""), s.get("duration_ms"),
                        ev.get("screenshot_url", ""), ev.get("trace_url", "")])
    return buf.getvalue()


# ── JUnit XML ────────────────────────────────────────────────────────────────

#: Our seven statuses onto JUnit's four. Documented because it is LOSSY:
#: `<failure>` = a verdict about the APPLICATION; `<error>` = our automation,
#: environment or an unproven cause. A CI gate can therefore distinguish
#: "your product broke" from "the test tooling broke" — a distinction plain
#: JUnit consumers otherwise lose entirely.
_JUNIT_MAP = {
    ST_PASSED: "pass",
    ST_DEFECT: "failure",
    ST_COMPLETED_WITH_DEFECTS: "failure",
    ST_DEFECT_HALTED: "failure",
    ST_EXEC_ERROR: "error",
    ST_NEEDS_REVIEW: "error",
    ST_BLOCKED: "skipped",
    ST_SKIPPED: "skipped",
    ST_CANCELLED: "skipped",
    ST_NOT_EXECUTED: "skipped",
}


def to_junit_xml(report: dict) -> str:
    summary = report.get("summary") or {}
    run = report.get("run") or {}
    cases_xml: list[str] = []
    n_fail = n_err = n_skip = 0
    for flow, case in _iter_cases(report):
        kind = _JUNIT_MAP.get(case.get("status"), "error")
        secs = round((case.get("duration_ms") or 0) / 1000.0, 3)
        name = _xml_escape(str(case.get("name") or case.get("test_case_id") or ""))
        cls = _xml_escape(str(flow.get("flow_label") or "flow"))
        props = (
            f'<properties>'
            f'<property name="nexus.status" value="{_xml_escape(str(case.get("status")))}"/>'
            f'<property name="nexus.test_type" value="{_xml_escape(str(case.get("test_type") or ""))}"/>'
            f'<property name="nexus.test_case_id" value="{_xml_escape(str(case.get("test_case_id") or ""))}"/>'
            f'</properties>')
        body = props
        if kind == "failure":
            n_fail += 1
            det = "; ".join(
                f'step {s.get("step_number")}: {s.get("actual", "")[:200]}'
                for s in (case.get("steps") or []) if s.get("status") == ST_DEFECT)
            body += (f'<failure type="application_defect" '
                     f'message="{_xml_escape(det[:400] or "application defect")}"/>')
        elif kind == "error":
            n_err += 1
            det = "; ".join(
                f'step {s.get("step_number")}: {s.get("actual", "")[:200]}'
                for s in (case.get("steps") or [])
                if s.get("status") in (ST_EXEC_ERROR, ST_NEEDS_REVIEW))
            body += (f'<error type="{_xml_escape(str(case.get("status")))}" '
                     f'message="{_xml_escape(det[:400] or "execution error / needs review")}"/>')
        elif kind == "skipped":
            n_skip += 1
            body += (f'<skipped message="'
                     f'{_xml_escape(str(case.get("not_executed_reason") or case.get("status")))}"/>')
        cases_xml.append(
            f'<testcase classname="{cls}" name="{name}" time="{secs}">{body}</testcase>')
    total = len(cases_xml)
    return (
        '<?xml version="1.0" encoding="UTF-8"?>\n'
        '<!-- Lossy by design: JUnit has 4 outcomes, this report has 7.\n'
        '     <failure> = a verdict about the APPLICATION UNDER TEST.\n'
        '     <error>   = our automation/environment, or a cause we could not prove.\n'
        '     The precise class is in each testcase\'s <properties>. -->\n'
        f'<testsuites name="nexus-evidence" tests="{total}" failures="{n_fail}" '
        f'errors="{n_err}" skipped="{n_skip}">\n'
        f'  <testsuite name="{_xml_escape(str(summary.get("artifact_id") or "artifact"))}" '
        f'tests="{total}" failures="{n_fail}" errors="{n_err}" skipped="{n_skip}" '
        f'timestamp="{_xml_escape(str(run.get("started_at") or ""))}">\n    '
        + "\n    ".join(cases_xml) +
        '\n  </testsuite>\n</testsuites>\n')


# ── XLSX (openpyxl) ──────────────────────────────────────────────────────────

def to_xlsx(report: dict) -> bytes:
    """Multi-sheet workbook: Summary, Cases, Steps, Defects."""
    from openpyxl import Workbook
    from openpyxl.styles import Font

    wb = Workbook()
    bold = Font(bold=True)
    summary = report.get("summary") or {}
    trust = report.get("trust") or {}
    analytics = build_analytics(report)

    ws = wb.active
    ws.title = "Summary"
    rows = [
        ("Execution Evidence Report", ""),
        ("Artifact", summary.get("artifact_id")),
        ("Run", (report.get("run") or {}).get("run_id")),
        ("Environment", (report.get("run") or {}).get("environment")),
        ("Generated", report.get("generated_at")),
        ("", ""),
        ("TRUST", ""),
        ("Certified before judging the app", "YES" if trust.get("certified") else "NOT YET"),
        ("Certification run", (trust.get("certification_run") or {}).get("run_id")),
        ("Quarantined cases", trust.get("quarantined_count")),
        ("Uncertified exploratory", trust.get("uncertified_exploratory_count")),
        ("", ""),
        ("CASE COUNTS (all seven buckets)", ""),
    ]
    for k in TRIPLET_KEYS:
        rows.append((k, (summary.get("case_counts") or {}).get(k, 0)))
    rows += [("not_executed", (summary.get("case_counts") or {}).get(ST_NOT_EXECUTED, 0)),
             ("", ""), ("ANALYTICS", ""),
             ("Pass rate % (of executed)", analytics["pass_rate_pct"]),
             ("Defect rate %", analytics["defect_rate_pct"]),
             ("Execution error rate %", analytics["execution_error_rate_pct"]),
             ("Avg case duration ms", analytics["avg_case_duration_ms"]),
             ("Longest case", analytics["longest_case"]["name"]),
             ("Slowest step", analytics["slowest_step"]["name"]),
             ("", ""), ("NOTE", analytics["honesty_note"])]
    for r in rows:
        ws.append(list(r))
    for c in ("A1", "A7", "A13"):
        ws[c].font = bold
    ws.column_dimensions["A"].width = 38
    ws.column_dimensions["B"].width = 70

    wc = wb.create_sheet("Cases")
    wc.append(["Flow", "Test case id", "Name", "Type", "Priority", "Status",
               "Executed", "Steps executed", "Steps declared", "Duration ms",
               "Not-executed reason"])
    for cell in wc[1]:
        cell.font = bold
    for flow, case in _iter_cases(report):
        wc.append([flow.get("flow_label"), case.get("test_case_id"), case.get("name"),
                   case.get("test_type"), case.get("priority"), case.get("status"),
                   bool(case.get("executed")), case.get("steps_executed"),
                   case.get("steps_declared"), case.get("duration_ms"),
                   case.get("not_executed_reason", "")])
    wc.column_dimensions["C"].width = 60

    wsx = wb.create_sheet("Steps")
    wsx.append(["Flow", "Case", "Step", "Status", "Badge", "Action", "Expected",
                "Actual / error", "Evidence class", "Category", "Cause",
                "AI-suggested", "Duration ms"])
    for cell in wsx[1]:
        cell.font = bold
    for flow, case in _iter_cases(report):
        for s in case.get("steps") or []:
            an = s.get("analysis") or {}
            wsx.append([flow.get("flow_label"), case.get("name"), s.get("step_number"),
                        s.get("status"), s.get("status_badge"),
                        str(s.get("action") or "")[:500],
                        str(s.get("expected") or "")[:500],
                        str(s.get("actual") or "")[:500], s.get("evidence_class"),
                        an.get("category", ""), an.get("cause", ""),
                        an.get("suggested", ""), s.get("duration_ms")])

    wd = wb.create_sheet("Defects")
    wd.append(["Signature", "Case", "Step", "Class", "Category", "Cause",
               "Lifecycle", "Occurrences", "First seen", "Last seen", "Shape"])
    for cell in wd[1]:
        cell.font = bold
    for d in ((report.get("defects") or {}).get("defects") or []):
        wd.append([d.get("signature"), d.get("case_name") or d.get("scenario_id"),
                   d.get("step_number"), d.get("display_status"), d.get("category"),
                   d.get("cause"), d.get("lifecycle"), d.get("occurrence_count"),
                   d.get("first_seen"), d.get("last_seen"),
                   str(d.get("fingerprint") or "")[:300]])

    out = io.BytesIO()
    wb.save(out)
    return out.getvalue()


# ── PDF (self-contained writer; no third-party dependency) ───────────────────

_PAGE_W, _PAGE_H = 595, 842          # A4 points
_MARGIN = 46
_LEAD = 13.2


def _pdf_escape(s: str) -> str:
    return (str(s).replace("\\", r"\\").replace("(", r"\(").replace(")", r"\)"))


def _wrap(text: str, width_chars: int) -> list[str]:
    words, lines, cur = str(text or "").split(), [], ""
    for w in words:
        if len(cur) + len(w) + 1 <= width_chars:
            cur = f"{cur} {w}".strip()
        else:
            if cur:
                lines.append(cur)
            cur = w[:width_chars] if len(w) > width_chars else w
    if cur:
        lines.append(cur)
    return lines or [""]


def to_pdf(report: dict) -> bytes:
    """A compact auditor's PDF (summary + trust + flows + defects + coverage).

    Written directly — no reportlab/weasyprint — so an air-gapped on-prem
    install can still produce the PDF an auditor asks for. Deliberately a
    SUMMARY: the full step-level evidence lives in the HTML/JSON/XLSX, and a
    5,000-row PDF helps nobody.
    """
    summary = report.get("summary") or {}
    trust = report.get("trust") or {}
    run = report.get("run") or {}
    analytics = build_analytics(report)
    cov = report.get("coverage") or {}

    # (text, size, style) — style: 0 body, 1 heading, 2 dim
    lines: list[tuple[str, int, int]] = [
        ("Execution Evidence Report", 17, 1),
        (f"Certificate of Execution · report v{report.get('report_version')} · "
         f"generated {report.get('generated_at')}", 8, 2),
        ("", 8, 0),
        ("Trust", 12, 1),
        (trust.get("statement", ""), 8, 2),
        (f"Certified: {'YES' if trust.get('certified') else 'NOT YET'}    "
         f"Certification run: {(trust.get('certification_run') or {}).get('run_id', '-')}", 9, 0),
        (f"Quarantined: {trust.get('quarantined_count')}    "
         f"Uncertified exploratory: {trust.get('uncertified_exploratory_count')}    "
         f"Suite size: {trust.get('suite_size')}", 9, 0),
        ("", 8, 0),
        ("Execution summary", 12, 1),
        (f"Artifact {summary.get('artifact_id')}   Run {run.get('run_id', '-')}   "
         f"Env {run.get('environment', '-')}", 9, 0),
        (f"Flows {summary.get('total_flows')}   Cases generated "
         f"{summary.get('total_cases_generated')}   Cases executed "
         f"{summary.get('total_cases_executed')}   Steps {summary.get('total_steps_executed')}", 9, 0),
        ("", 6, 0),
        ("Case outcomes (all seven buckets, zeros included):", 9, 0),
    ]
    cc = summary.get("case_counts") or {}
    lines.append(("   " + "   ".join(f"{k}={cc.get(k, 0)}" for k in TRIPLET_KEYS), 9, 0))
    if cc.get(ST_NOT_EXECUTED):
        lines.append((f"   not_executed={cc.get(ST_NOT_EXECUTED)}", 9, 0))
    sc = summary.get("step_counts") or {}
    lines += [("Step outcomes:", 9, 0),
              ("   " + "   ".join(f"{k}={sc.get(k, 0)}" for k in TRIPLET_KEYS), 9, 0),
              ("A step that did not execute is never counted as a pass.", 8, 2),
              ("", 8, 0), ("Analytics", 12, 1),
              (f"Pass rate {analytics['pass_rate_pct']}%   "
               f"Defect rate {analytics['defect_rate_pct']}%   "
               f"Execution-error rate {analytics['execution_error_rate_pct']}%", 9, 0),
              (f"Avg case {analytics['avg_case_duration_ms']} ms   "
               f"Longest: {analytics['longest_case']['name'][:60]}", 9, 0),
              (f"Evidence classes: {analytics['evidence_class_distribution']}", 9, 0),
              (analytics["honesty_note"], 8, 2), ("", 8, 0), ("Flows", 12, 1)]

    for f in report.get("flows") or []:
        lines.append((f"{f.get('flow_label')} — {f.get('case_count')} cases, "
                      f"pass {f.get('pass_percentage')}%, defects {f.get('defect_count')}", 9, 0))

    # Per-case roll: an audit PDF that never says WHICH cases ran, and how each
    # ended, is not an audit artifact. Every case is listed (pagination handles
    # a large suite) with its status and step tally — the step-by-step evidence
    # stays in the HTML/JSON/XLSX.
    lines += [("", 8, 0), ("Test cases", 12, 1),
              ("Every generated case is listed, including those that did not run.", 8, 2)]
    for flow, case in _iter_cases(report):
        cnt = case.get("counts") or {}
        tally = " ".join(f"{k[:4]}={cnt.get(k, 0)}" for k in TRIPLET_KEYS
                         if cnt.get(k, 0))
        head = (f"  [{case.get('status')}] {str(case.get('name') or '')[:72]}")
        lines.append((head, 8, 0))
        detail = (f"      {flow.get('flow_label')} · {case.get('test_type')} · "
                  f"{case.get('steps_executed')}/{case.get('steps_declared')} steps · "
                  f"{case.get('duration_ms')} ms{('  · ' + tally) if tally else ''}")
        if not case.get("executed"):
            detail += f"  · NOT EXECUTED: {case.get('not_executed_reason', '')}"
        for ln in _wrap(detail, 112)[:2]:
            lines.append((ln, 7, 2))

    d = report.get("defects") or {}
    if d:
        lines += [("", 8, 0), ("Defects (deduplicated)", 12, 1),
                  (f"{d.get('unique_defects')} unique across "
                   f"{d.get('total_occurrences')} occurrences in "
                   f"{d.get('window_runs')} runs — lifecycle {d.get('by_lifecycle')}", 9, 0)]
        for x in (d.get("defects") or [])[:12]:
            lines.append((f"  [{x.get('display_status')}] {str(x.get('case_name') or x.get('scenario_id'))[:52]} "
                          f"step {x.get('step_number')} ×{x.get('occurrence_count')} "
                          f"({x.get('lifecycle')})", 8, 0))
            for ln in _wrap(f"cause: {x.get('cause')} — {x.get('fingerprint')}", 105)[:2]:
                lines.append(("      " + ln, 7, 2))
    lines += [("", 8, 0), ("Coverage honesty", 12, 1),
              (str(cov.get("note", "")), 8, 2),
              (f"Cases not executed: {cov.get('cases_not_executed_count')}   "
               f"Quarantined: {cov.get('quarantined_count')}   "
               f"Uncertified exploratory: {cov.get('uncertified_exploratory_count')}", 9, 0)]
    for x in (cov.get("cases_not_executed") or [])[:14]:
        for ln in _wrap(f"- {x.get('name')} — {x.get('reason')}", 100)[:2]:
            lines.append(("   " + ln, 7, 2))

    # ── paginate ────────────────────────────────────────────────────────────
    pages: list[list[tuple[str, int, int]]] = [[]]
    y = _PAGE_H - _MARGIN
    for item in lines:
        need = _LEAD if item[1] <= 9 else _LEAD + 6
        if y - need < _MARGIN + 24:
            pages.append([])
            y = _PAGE_H - _MARGIN
        pages[-1].append(item)
        y -= need

    streams: list[bytes] = []
    for pno, page in enumerate(pages, 1):
        parts = ["BT"]
        y = _PAGE_H - _MARGIN
        for text, size, style in page:
            font = "/F2" if style == 1 else "/F1"
            gray = " 0.42 g" if style == 2 else " 0 g"
            need = _LEAD if size <= 9 else _LEAD + 6
            y -= need
            parts.append(f"1 0 0 1 {_MARGIN} {y:.1f} Tm{gray} {font} {size} Tf "
                         f"({_pdf_escape(text)}) Tj")
        parts.append(f"1 0 0 1 {_MARGIN} {_MARGIN - 8} Tm 0.55 g /F1 7 Tf "
                     f"({_pdf_escape(f'Page {pno} of {len(pages)} · integrity: see manifest.json in the evidence package')}) Tj")
        parts.append("ET")
        streams.append(zlib.compress("\n".join(parts).encode("latin-1", "replace")))

    objs: list[bytes] = []
    n_pages = len(streams)
    font_regular = 3 + 2 * n_pages + 1
    font_bold = font_regular + 1
    kids = " ".join(f"{3 + 2 * i} 0 R" for i in range(n_pages))
    objs.append(b"<< /Type /Catalog /Pages 2 0 R >>")
    objs.append(f"<< /Type /Pages /Kids [{kids}] /Count {n_pages} >>".encode())
    for i, st in enumerate(streams):
        objs.append((f"<< /Type /Page /Parent 2 0 R /MediaBox [0 0 {_PAGE_W} {_PAGE_H}] "
                     f"/Resources << /Font << /F1 {font_regular} 0 R /F2 {font_bold} 0 R >> >> "
                     f"/Contents {4 + 2 * i} 0 R >>").encode())
        objs.append(b"<< /Length " + str(len(st)).encode() +
                    b" /Filter /FlateDecode >>\nstream\n" + st + b"\nendstream")
    objs.append(b"<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica /Encoding /WinAnsiEncoding >>")
    objs.append(b"<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica-Bold /Encoding /WinAnsiEncoding >>")

    out = io.BytesIO()
    out.write(b"%PDF-1.4\n%\xe2\xe3\xcf\xd3\n")
    offsets = [0]
    for i, body in enumerate(objs, 1):
        offsets.append(out.tell())
        out.write(f"{i} 0 obj\n".encode() + body + b"\nendobj\n")
    xref_at = out.tell()
    out.write(f"xref\n0 {len(objs) + 1}\n".encode())
    out.write(b"0000000000 65535 f \n")
    for off in offsets[1:]:
        out.write(f"{off:010d} 00000 n \n".encode())
    out.write(f"trailer\n<< /Size {len(objs) + 1} /Root 1 0 R >>\nstartxref\n"
              f"{xref_at}\n%%EOF\n".encode())
    return out.getvalue()


__all__ = ["build_analytics", "filter_report", "to_csv", "to_junit_xml",
           "to_xlsx", "to_pdf"]
