"""Storyboard Phase 1 — additive derivation tables over the frozen canonical pipeline.

The canonical pipeline (v1.0-gpu-validated) writes raw visual evidence to
``visual_frames``, ``visual_scenes``, ``app_instances``, ``evidence_controls``,
``evidence_steps``, ``cursor_events``, ``visual_flows`` and ``visual_flow_edges``.

Storyboard Phase 1 introduces FOUR additive derivation tables on top of that
data.  None of the pipeline tables are modified — these tables are populated
post-pipeline by ``platform/api/app/services/storyboard/`` and consumed by the
new ``/api/v1/artifacts/{id}/storyboard`` endpoint and the new
``/api/v1/artifacts/{id}/frames/{frame_id}/annotated.png`` endpoint.

storyboard_panels
    Compressed scene groupings.  The pipeline emits N raw scenes (often noisy
    with repeated "New Tab" or duplicate-form-fill scenes).  The scene grouper
    collapses adjacent same-screen scenes into one panel and surfaces a
    representative frame + caption + in-scene action count.  This is the
    primary unit the storyboard UI renders.

app_groupings
    Dedup'd app instances.  The pipeline detects boundaries from window-title
    OCR which produces fakes like ``Wivwquardianlife.com`` vs
    ``www.guardianlife.com``.  The deduper fuzzy-matches these into canonical
    ``guardianlife.com`` groupings keyed by registered-domain-or-equivalent.

scene_captions
    Short imperative captions per scene (5-8 words, e.g. ``"Filled email
    field"``).  Generated by an LLM rewriter that consumes
    ``scene_state_summary`` + edge ``primary_action_summary`` + evidence_steps
    digest.  Verbose LLaVA descriptions are NOT used as captions (they read
    "The interface displays a form with...") — they are an INPUT signal to
    the rewriter.

annotated_frame_cache
    Metadata for cached annotated frame PNGs.  The actual PNG (cursor +
    click marker + OCR boxes baked in) lives in the same object store as
    the raw frame, under an ``annotated/`` prefix.  This table stores the
    asset path, render version and signal manifest so the API can answer
    "is there a fresh annotated PNG for this frame?" without round-tripping
    to the object store.

All four tables follow established conventions:

  * tenant_id on every row + RLS policy (matching migration 029)
  * Deterministic uuid5 primary keys → idempotent UPSERT semantics
  * Version columns (``grouper_version``, ``deduper_version``,
    ``generator_version``, ``annotation_version``) — bumping a version
    string forces re-derivation without DDL
  * ON DELETE CASCADE from canonical_artifacts → tenant offboarding is clean
  * created_at + updated_at timestamps

Revision ID: 030_storyboard_phase1
Revises: 029_visual_evidence_rls
Create Date: 2026-05-23
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects.postgresql import JSONB


revision: str = "030_storyboard_phase1"
down_revision: Union[str, None] = "029_visual_evidence_rls"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


_STORYBOARD_TABLES = [
    "storyboard_panels",
    "app_groupings",
    "scene_captions",
    "annotated_frame_cache",
]


def upgrade() -> None:
    # ── app_groupings ────────────────────────────────────────────────────────
    # Created first because storyboard_panels has an FK reference to it.
    op.create_table(
        "app_groupings",
        sa.Column("grouping_id", sa.String(64), primary_key=True),
        sa.Column(
            "artifact_id",
            sa.String(64),
            sa.ForeignKey("canonical_artifacts.artifact_id", ondelete="CASCADE"),
            nullable=False,
        ),
        sa.Column("tenant_id", sa.String(64), nullable=False),
        sa.Column("session_id", sa.String(64), nullable=False),
        # Cleaned, human-facing label e.g. "Guardian Life Insurance".
        sa.Column("canonical_name", sa.String(500), nullable=False, server_default=""),
        # Cleaned eTLD+1 e.g. "guardianlife.com".  Empty for desktop apps.
        sa.Column("canonical_domain", sa.String(500), nullable=False, server_default=""),
        # web_ui | mobile | desktop | terminal | unknown.  Mirrors the
        # vocabulary used by app_instances.app_type so downstream consumers
        # can reuse existing renderers.
        sa.Column("app_type", sa.String(50), nullable=False, server_default="unknown"),
        # Display label shown in storyboard panels and AppTimeline lanes.
        # May differ from canonical_name when the SME's recording shows a
        # branded product name distinct from the domain.
        sa.Column("display_label", sa.String(500), nullable=False, server_default=""),
        # Original app_instance.instance_id values merged into this grouping.
        sa.Column(
            "member_instance_ids",
            JSONB,
            nullable=False,
            server_default=sa.text("'[]'::jsonb"),
        ),
        sa.Column("total_scene_count", sa.Integer, nullable=False, server_default="0"),
        sa.Column("first_scene_index", sa.Integer, nullable=False, server_default="0"),
        sa.Column("last_scene_index", sa.Integer, nullable=False, server_default="0"),
        # 0..1 confidence in this grouping.  Combines the worst original
        # segmentation_confidence with the deduper's similarity score.
        sa.Column("confidence", sa.Float, nullable=False, server_default="1.0"),
        # exact_domain | fuzzy_domain | window_title_normalized |
        # single_instance | desktop_app_grouping
        sa.Column(
            "dedup_basis", sa.String(50), nullable=False, server_default="single_instance",
        ),
        # Audit trail: original strings + similarity metrics.  Helps when an
        # operator disputes a grouping ("why was Citibank merged with
        # Citizens Bank?").
        sa.Column(
            "dedup_evidence",
            JSONB,
            nullable=False,
            server_default=sa.text("'{}'::jsonb"),
        ),
        # Bump this in env config (STORYBOARD_APP_DEDUP_VERSION) to force
        # re-derivation of every grouping in the database.
        sa.Column("deduper_version", sa.String(50), nullable=False, server_default="v1"),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.text("now()"),
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.text("now()"),
        ),
    )
    op.create_index(
        "ix_app_groupings_artifact", "app_groupings", ["artifact_id"],
    )
    op.create_index(
        "ix_app_groupings_tenant_session",
        "app_groupings",
        ["tenant_id", "session_id"],
    )
    op.create_index(
        "ix_app_groupings_canonical_domain",
        "app_groupings",
        ["tenant_id", "canonical_domain"],
    )

    # ── storyboard_panels ────────────────────────────────────────────────────
    op.create_table(
        "storyboard_panels",
        sa.Column("panel_id", sa.String(64), primary_key=True),
        sa.Column(
            "artifact_id",
            sa.String(64),
            sa.ForeignKey("canonical_artifacts.artifact_id", ondelete="CASCADE"),
            nullable=False,
        ),
        sa.Column("tenant_id", sa.String(64), nullable=False),
        sa.Column("session_id", sa.String(64), nullable=False),
        # 0-based chronological index within the artifact's storyboard.
        sa.Column("panel_index", sa.Integer, nullable=False),
        # The range of raw scenes this panel collapses.  When scene_count == 1
        # the panel maps to a single raw scene; otherwise N adjacent scenes
        # were merged because they showed the same screen.
        sa.Column(
            "first_scene_id",
            sa.String(64),
            sa.ForeignKey("visual_scenes.scene_id", ondelete="CASCADE"),
            nullable=False,
        ),
        sa.Column(
            "last_scene_id",
            sa.String(64),
            sa.ForeignKey("visual_scenes.scene_id", ondelete="CASCADE"),
            nullable=False,
        ),
        sa.Column("scene_count", sa.Integer, nullable=False, server_default="1"),
        # Link to the dedup'd app this panel belongs to.  Null when the
        # scenes had no resolvable app_instance (rare; usually a pipeline
        # gap).
        sa.Column(
            "app_grouping_id",
            sa.String(64),
            sa.ForeignKey("app_groupings.grouping_id", ondelete="SET NULL"),
            nullable=True,
        ),
        # The single best-quality frame to render as the panel hero.  Picked
        # from across all collapsed scenes by the scene grouper.
        sa.Column(
            "representative_frame_id",
            sa.String(64),
            sa.ForeignKey("visual_frames.frame_id", ondelete="SET NULL"),
            nullable=True,
        ),
        sa.Column(
            "representative_frame_asset_path",
            sa.String(1000),
            nullable=False,
            server_default="",
        ),
        # Time range in milliseconds relative to session start.
        sa.Column("start_ms", sa.Integer, nullable=False, server_default="0"),
        sa.Column("end_ms", sa.Integer, nullable=False, server_default="0"),
        sa.Column("duration_ms", sa.Integer, nullable=False, server_default="0"),
        # Short imperative caption.  May be empty until the caption rewriter
        # has run; UI falls back to scene_state_summary.screen_title.
        sa.Column("caption_short", sa.Text, nullable=False, server_default=""),
        # Optional longer narrative.  Used in drill-down detail panels.
        sa.Column("caption_long", sa.Text, nullable=False, server_default=""),
        # Number of evidence_steps that fired inside this panel's scene range.
        # Drives the "filled 97 fields" headline in the drill-down view.
        sa.Column(
            "in_scene_action_count", sa.Integer, nullable=False, server_default="0",
        ),
        # strong | degraded | weak — mirrors VisualSceneRow.scene_quality
        # semantics so existing ConfidenceChip components render identically.
        sa.Column(
            "panel_quality", sa.String(20), nullable=False, server_default="weak",
        ),
        sa.Column(
            "completeness_confidence", sa.Float, nullable=False, server_default="0.0",
        ),
        # Noise filter — panels flagged as noise are hidden from the default
        # storyboard but available behind a "show noise" toggle.  Reason is
        # a free-form string so the grouper can evolve without DB changes
        # (e.g. ``blank_browser_tab``, ``duplicate_screen``,
        # ``ocr_confidence_below_threshold``).
        sa.Column(
            "is_noise", sa.Boolean, nullable=False, server_default=sa.text("false"),
        ),
        sa.Column("noise_reason", sa.String(200), nullable=False, server_default=""),
        # Bump STORYBOARD_SCENE_GROUPER_VERSION in env config to force every
        # artifact to be re-grouped.  The composer compares this against the
        # configured version and triggers re-derivation when stale.
        sa.Column(
            "grouper_version", sa.String(50), nullable=False, server_default="v1",
        ),
        # Detector-specific JSON so the grouper can evolve without DDL.
        # Currently includes: collapse_reason, scene_id_members,
        # ocr_jaccard_similarity, hash_similarity, etc.
        sa.Column(
            "grouper_signals",
            JSONB,
            nullable=False,
            server_default=sa.text("'{}'::jsonb"),
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.text("now()"),
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.text("now()"),
        ),
        sa.UniqueConstraint(
            "artifact_id", "panel_index", name="uq_storyboard_panels_artifact_index",
        ),
    )
    op.create_index(
        "ix_storyboard_panels_artifact_panel",
        "storyboard_panels",
        ["artifact_id", "panel_index"],
    )
    op.create_index(
        "ix_storyboard_panels_tenant_session",
        "storyboard_panels",
        ["tenant_id", "session_id"],
    )
    op.create_index(
        "ix_storyboard_panels_app_grouping", "storyboard_panels", ["app_grouping_id"],
    )

    # ── scene_captions ───────────────────────────────────────────────────────
    op.create_table(
        "scene_captions",
        sa.Column("caption_id", sa.String(64), primary_key=True),
        sa.Column(
            "scene_id",
            sa.String(64),
            sa.ForeignKey("visual_scenes.scene_id", ondelete="CASCADE"),
            nullable=False,
        ),
        sa.Column(
            "artifact_id",
            sa.String(64),
            sa.ForeignKey("canonical_artifacts.artifact_id", ondelete="CASCADE"),
            nullable=False,
        ),
        sa.Column("tenant_id", sa.String(64), nullable=False),
        # 5-8 word imperative caption ("Filled email field", "Submitted quote
        # form").  Empty string is allowed; UI falls back to screen_title.
        sa.Column("short_caption", sa.Text, nullable=False, server_default=""),
        # Optional fuller sentence ("The user filled the email field with
        # 'john@x.com' and tabbed to the password input.").  Drives the
        # drill-down narrative.
        sa.Column("narrative_caption", sa.Text, nullable=False, server_default=""),
        # strong | degraded | weak — when weak, UI may grey the caption or
        # show "needs review" badge.
        sa.Column(
            "caption_quality", sa.String(20), nullable=False, server_default="weak",
        ),
        # Fully-qualified model identifier (e.g. ``ollama/llama3.2:3b``,
        # ``openai/gpt-4o-mini``).  Stamped at generation time so future
        # backfills can target specific outdated rows.
        sa.Column(
            "generator_model", sa.String(100), nullable=False, server_default="",
        ),
        # Bump STORYBOARD_CAPTION_VERSION to force re-generation of all
        # captions.  Used for prompt-template changes or rewriter logic
        # updates.
        sa.Column(
            "generator_version", sa.String(50), nullable=False, server_default="v1",
        ),
        # Snapshot of the input signals fed to the rewriter — helps debug
        # bad captions and supports re-running offline against persisted
        # inputs.
        sa.Column(
            "input_signals",
            JSONB,
            nullable=False,
            server_default=sa.text("'{}'::jsonb"),
        ),
        # Observability: how long the LLM call took.  Captured as integer
        # milliseconds so we can SUM/AVG cheaply.
        sa.Column(
            "generation_latency_ms",
            sa.Integer,
            nullable=False,
            server_default="0",
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.text("now()"),
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.text("now()"),
        ),
        sa.UniqueConstraint(
            "scene_id", "generator_version", name="uq_scene_captions_scene_version",
        ),
    )
    op.create_index(
        "ix_scene_captions_artifact", "scene_captions", ["artifact_id"],
    )
    op.create_index(
        "ix_scene_captions_tenant", "scene_captions", ["tenant_id"],
    )

    # ── annotated_frame_cache ────────────────────────────────────────────────
    op.create_table(
        "annotated_frame_cache",
        sa.Column("cache_id", sa.String(64), primary_key=True),
        sa.Column(
            "frame_id",
            sa.String(64),
            sa.ForeignKey("visual_frames.frame_id", ondelete="CASCADE"),
            nullable=False,
        ),
        sa.Column(
            "artifact_id",
            sa.String(64),
            sa.ForeignKey("canonical_artifacts.artifact_id", ondelete="CASCADE"),
            nullable=False,
        ),
        sa.Column("tenant_id", sa.String(64), nullable=False),
        # Bump STORYBOARD_ANNOTATION_VERSION to invalidate every cached PNG
        # without dropping rows (the asset path includes the version, so
        # new renders write to a new path and old paths can be garbage
        # collected lazily).
        sa.Column(
            "annotation_version", sa.String(50), nullable=False, server_default="v1",
        ),
        # Object-store relative path for the annotated PNG.  Pattern:
        # ``{tenant}/{session}/wf/{workflow}/annotated/v{version}/{frame_id}.png``
        sa.Column("asset_path", sa.String(1000), nullable=False),
        sa.Column(
            "content_type", sa.String(50), nullable=False, server_default="image/png",
        ),
        sa.Column("width_px", sa.Integer, nullable=False, server_default="0"),
        sa.Column("height_px", sa.Integer, nullable=False, server_default="0"),
        sa.Column("size_bytes", sa.Integer, nullable=False, server_default="0"),
        # Which annotations were rendered.  Keys:
        #   cursor_marker (bool)  — was a cursor drawn?
        #   click_marker (bool)   — was a click point highlighted?
        #   ocr_boxes (int)       — count of OCR bounding boxes drawn
        #   caption_band (bool)   — was the caption banner rendered?
        #   action_target (bool)  — was the action target highlighted?
        sa.Column(
            "annotation_signals",
            JSONB,
            nullable=False,
            server_default=sa.text("'{}'::jsonb"),
        ),
        sa.Column(
            "render_latency_ms", sa.Integer, nullable=False, server_default="0",
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.text("now()"),
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.text("now()"),
        ),
        sa.UniqueConstraint(
            "frame_id", "annotation_version",
            name="uq_annotated_frame_cache_frame_version",
        ),
    )
    op.create_index(
        "ix_annotated_frame_cache_artifact",
        "annotated_frame_cache",
        ["artifact_id"],
    )
    op.create_index(
        "ix_annotated_frame_cache_tenant", "annotated_frame_cache", ["tenant_id"],
    )

    # ── Row-Level Security on all four tables ────────────────────────────────
    # Mirrors the pattern from migration 029_visual_evidence_rls.py.  Each
    # statement is wrapped in a DO-block so a missing dependency is a NOTICE
    # not a hard failure (e.g. on a partial deploy where the nexus_app role
    # has not been created yet).
    for table in _STORYBOARD_TABLES:
        op.execute(f"""
            DO $$
            BEGIN
                IF EXISTS (
                    SELECT FROM information_schema.tables
                    WHERE table_schema = 'public' AND table_name = '{table}'
                ) THEN
                    ALTER TABLE {table} ENABLE ROW LEVEL SECURITY;
                    ALTER TABLE {table} FORCE ROW LEVEL SECURITY;

                    DROP POLICY IF EXISTS tenant_isolation ON {table};
                    CREATE POLICY tenant_isolation ON {table}
                        USING (tenant_id = current_setting('nexus.current_tenant_id', true))
                        WITH CHECK (tenant_id = current_setting('nexus.current_tenant_id', true));

                    IF EXISTS (
                        SELECT FROM pg_roles WHERE rolname = 'nexus_app'
                    ) THEN
                        GRANT SELECT, INSERT, UPDATE, DELETE ON {table} TO nexus_app;
                    END IF;
                END IF;
            END$$;
        """)


def downgrade() -> None:
    # Drop in reverse order so FKs unwind cleanly.
    op.drop_index("ix_annotated_frame_cache_tenant", table_name="annotated_frame_cache")
    op.drop_index("ix_annotated_frame_cache_artifact", table_name="annotated_frame_cache")
    op.drop_table("annotated_frame_cache")

    op.drop_index("ix_scene_captions_tenant", table_name="scene_captions")
    op.drop_index("ix_scene_captions_artifact", table_name="scene_captions")
    op.drop_table("scene_captions")

    op.drop_index("ix_storyboard_panels_app_grouping", table_name="storyboard_panels")
    op.drop_index("ix_storyboard_panels_tenant_session", table_name="storyboard_panels")
    op.drop_index("ix_storyboard_panels_artifact_panel", table_name="storyboard_panels")
    op.drop_table("storyboard_panels")

    op.drop_index("ix_app_groupings_canonical_domain", table_name="app_groupings")
    op.drop_index("ix_app_groupings_tenant_session", table_name="app_groupings")
    op.drop_index("ix_app_groupings_artifact", table_name="app_groupings")
    op.drop_table("app_groupings")
