"""Cypress exporter (P5).

Emits one ``<app>.cy.ts`` per app_instance, packaged in a ZIP.  Cypress
uses ``cy.get(selector).click() / .type() / .should('be.visible')`` —
selectors come straight from EvidenceControl.playwright_selector, which
is generic enough to work in both frameworks (CSS / xpath).
"""
from __future__ import annotations

import io
import json
import zipfile

from .base import ExportBundle, TestExporter, safe_name
from .preparation import ACTIONABLE_STEP_TYPES, PROOF_CONFIDENCE_THRESHOLD


def _build_cy_ts(
    app_name: str, test_cases: list[dict], controls_by_id: dict[str, dict],
) -> str:
    total = sum(len(tc.get("steps", [])) for tc in test_cases)
    proven = sum(
        1 for tc in test_cases
        for step in tc.get("steps", [])
        if step.get("evidence_scene_id")
        and step.get("proof_confidence", 0) >= PROOF_CONFIDENCE_THRESHOLD
    )

    lines = [
        "/// <reference types=\"cypress\" />",
        "",
        f"// App: {app_name}",
        f"// {proven} of {total} steps automation-ready.",
        "// Generated by Nexus QA Visual Evidence Pipeline (visual_strict).",
        "",
        f"describe({json.dumps(app_name)}, () => {{",
    ]

    for tc in test_cases:
        tc_title = tc.get("title") or "Unnamed test"
        scenario_id = tc.get("scenario_id") or ""
        # P6: embed scenario_id for CI ingest re-correlation.
        test_name = f"{scenario_id} — {tc_title}" if scenario_id else tc_title
        lines.append(f"  it({json.dumps(test_name)}, () => {{")

        for step in tc.get("steps", []):
            action = step.get("action") or ""
            selector = step.get("target_element") or ""
            expected = step.get("expected_output") or ""
            input_value = step.get("input_data") or ""
            scene_id = step.get("evidence_scene_id") or ""
            ctrl_id = step.get("evidence_control_id") or ""
            edge_id = step.get("evidence_edge_id") or ""
            conf = step.get("proof_confidence", 0.0) or 0.0
            action_lower = action.lower()

            ctrl = controls_by_id.get(ctrl_id)
            is_actionable = any(kw in action_lower for kw in ACTIONABLE_STEP_TYPES)
            passes_gate = (
                is_actionable
                and scene_id and ctrl_id
                and conf >= PROOF_CONFIDENCE_THRESHOLD
                and ctrl and ctrl.get("automation_ready")
                and expected
            )

            evidence_comment = (
                f"    // Evidence: scene_id={scene_id[:8] if scene_id else 'none'}, "
                f"edge_id={edge_id[:8] if edge_id else 'none'}, "
                f"confidence={conf:.2f}"
            )

            if is_actionable and not passes_gate:
                if not scene_id:
                    reason = "no evidence_scene_id"
                elif not ctrl_id:
                    reason = "no evidence_control_id"
                elif conf < PROOF_CONFIDENCE_THRESHOLD:
                    reason = f"proof_confidence={conf:.2f} below threshold"
                elif not ctrl or not ctrl.get("automation_ready"):
                    reason = "selector not OCR-backed"
                elif not expected:
                    reason = "no expected_output"
                else:
                    reason = "gate check failed"
                lines.append(evidence_comment)
                lines.append(
                    f"    cy.log({json.dumps('SKIPPED — UNPROVEN: ' + reason)});"
                )
                continue

            lines.append(evidence_comment)
            if selector:
                if any(kw in action_lower for kw in ("fill", "type", "enter", "input")):
                    if input_value:
                        lines.append(
                            f"    cy.get({json.dumps(selector)}).clear().type({json.dumps(input_value)});"
                        )
                    else:
                        lines.append(
                            f"    cy.get({json.dumps(selector)}).clear();"
                        )
                elif any(kw in action_lower for kw in ("select", "choose")):
                    lines.append(
                        f"    cy.get({json.dumps(selector)}).select({json.dumps(input_value)});"
                    )
                elif any(kw in action_lower for kw in ("verify", "assert", "check", "expect", "should")):
                    lines.append(
                        f"    cy.get({json.dumps(selector)}).should('be.visible');"
                    )
                else:
                    lines.append(
                        f"    cy.get({json.dumps(selector)}).click();"
                    )
            else:
                lines.append(f"    // TODO: automate — {action}")

            if expected:
                lines.append(
                    f"    cy.contains({json.dumps(expected[:120])}).should('be.visible');"
                )

        lines.append("  });")

    lines.append("});")
    lines.append("")
    return "\n".join(lines)


def _build_url_coverage_cy(
    page_visits: list[dict],
    page_actions: dict[str, list[dict]],
    form_snapshots: dict[str, dict],
) -> str:
    """Emit a Cypress spec walking the URL log + asserting form snapshots.

    Same idea as the Playwright variant — one ``it`` per distinct URL
    visited, with cy.visit + assertions derived from the form snapshot.
    """
    if not page_visits:
        return ""

    lines: list[str] = [
        "/// <reference types=\"cypress\" />",
        "",
        "// URL Coverage — generated from Phase 2 page_visits + form_snapshots.",
        "// One spec block per distinct URL visited.",
        "",
        "describe('URL Coverage', () => {",
    ]

    for visit in page_visits:
        location = (visit.get("location") or "").strip()
        if not location:
            continue
        seq = visit.get("sequence_index")
        visit_id = visit.get("page_visit_id") or ""
        snapshot = form_snapshots.get(visit_id) or {}
        intent = (snapshot.get("page_intent") or "").strip()
        test_title = " — ".join(p for p in [
            f"#{seq:02d}" if isinstance(seq, int) else f"#{seq}",
            intent,
            location,
        ] if p)

        lines.append(f"  it({json.dumps(test_title)}, () => {{")
        if location.startswith("http://") or location.startswith("https://"):
            lines.append(f"    cy.visit({json.dumps(location)});")
        else:
            lines.append(
                f"    // Native UI page — runner must open: {location}"
            )

        fields: dict[str, str] = snapshot.get("fields") or {}
        field_kinds: dict[str, str] = snapshot.get("field_kinds") or {}
        if fields:
            lines.append("    // Final form snapshot for this page:")
            for label, value in fields.items():
                if not label:
                    continue
                kind = (field_kinds.get(label) or "other").lower()
                value_str = str(value or "")
                label_re = json.dumps(label)
                if kind in ("checkbox", "radio"):
                    if value_str.lower() in ("true", "on", "yes", "checked"):
                        lines.append(
                            f"    cy.contains('label', {label_re}).find('input').should('be.checked');"
                        )
                    else:
                        lines.append(
                            f"    cy.contains('label', {label_re}).find('input').should('not.be.checked');"
                        )
                elif kind in ("dropdown", "text_field"):
                    if value_str:
                        lines.append(
                            f"    cy.contains('label', {label_re}).siblings('input,select').should('have.value', {json.dumps(value_str)});"
                        )
                    else:
                        lines.append(
                            f"    cy.contains({label_re}).should('be.visible');"
                        )
                else:
                    if value_str:
                        lines.append(
                            f"    cy.contains({json.dumps(value_str[:120])}).should('be.visible');"
                        )
                    else:
                        lines.append(
                            f"    cy.contains({json.dumps(label[:120])}).should('be.visible');"
                        )

        actions = page_actions.get(visit_id) or []
        if actions:
            lines.append("    // Captured actions on this page (for reference):")
            for action in actions:
                verb = (action.get("verb") or "").lower()
                target = (action.get("target_label") or "")[:120]
                value = action.get("value")
                value_repr = json.dumps(value) if value is not None else "null"
                lines.append(
                    f"    // - {verb}: target={json.dumps(target)} value={value_repr}"
                )

        lines.append("  });")

    lines.append("});")
    lines.append("")
    return "\n".join(lines)


class CypressExporter(TestExporter):
    format_id = "cypress"
    label = "Cypress (.cy.ts)"
    file_extension = "cy.ts"

    def render(self) -> ExportBundle:
        buf = io.BytesIO()
        with zipfile.ZipFile(buf, "w", zipfile.ZIP_DEFLATED) as zf:
            for inst_id, tcs in self.ctx.tc_by_inst.items():
                app_name = self.ctx.inst_name_map.get(inst_id, inst_id) or "App"
                spec = _build_cy_ts(app_name, tcs, self.ctx.controls_by_id)
                zf.writestr(f"{safe_name(app_name)}.cy.ts", spec)
            # Phase 2 — URL coverage spec, when extractor data is available.
            coverage = _build_url_coverage_cy(
                self.ctx.page_visits,
                self.ctx.page_actions,
                self.ctx.form_snapshots,
            )
            if coverage:
                zf.writestr("url-coverage.cy.ts", coverage)
        buf.seek(0)
        return ExportBundle(
            payload=buf.getvalue(),
            content_type="application/zip",
            filename=f"cypress-{self.ctx.artifact_id[:8]}.zip",
        )
