"""Gherkin (.feature) exporter (P5).

Emits one ``<app>.feature`` per app_instance, packaged in a ZIP. Plain-English
BDD-style scenarios derived from the visual evidence graph — perfect for
business stakeholder review and BDD teams (Cucumber, SpecFlow, Behave).

Each scenario step is rendered as Given / When / Then, with evidence
citation comments (``# Evidence: scene_id=...``) for traceability.
"""
from __future__ import annotations

import io
import zipfile

from .base import ExportBundle, TestExporter, safe_name


def _classify_step(action: str) -> str:
    """Pick Given/When/Then based on action verb."""
    a = (action or "").lower()
    if any(kw in a for kw in ("open", "navigate", "load", "visit", "go to", "is on")):
        return "Given"
    if any(kw in a for kw in (
        "click", "fill", "type", "enter", "input", "select",
        "choose", "submit", "press", "toggle", "drag", "upload",
    )):
        return "When"
    if any(kw in a for kw in (
        "verify", "assert", "check", "expect", "should",
        "see", "observe", "appears", "displayed",
    )):
        return "Then"
    return "And"


def _format_step_text(action: str, target: str, input_data: str) -> str:
    """Compose a human-readable step phrase from action + target + input."""
    parts = [(action or "").strip()]
    if target and target.strip().lower() not in (action or "").lower():
        parts.append(f'"{target.strip()}"')
    if input_data and input_data.strip():
        parts.append(f'with value "{input_data.strip()}"')
    return " ".join(p for p in parts if p)


def _build_feature(
    app_name: str, test_cases: list[dict],
) -> str:
    lines = [
        f"# App: {app_name}",
        "# Generated by Nexus QA Visual Evidence Pipeline (visual_strict).",
        "# Every step cites a specific scene + control from the recorded demo.",
        "",
        f"Feature: {app_name}",
        "",
    ]

    for tc in test_cases:
        title = tc.get("title") or "Unnamed scenario"
        strategy = tc.get("strategy") or "happy_path"
        proven = tc.get("visual_proven_steps")
        total = tc.get("visual_total_steps")

        tag = "@" + strategy.replace("_", "-")
        lines.append(f"  {tag}")
        lines.append(f"  Scenario: {title}")

        # Background-ish prefix: preconditions as Given lines
        for pre in tc.get("preconditions", []) or []:
            lines.append(f"    Given {pre}")

        prev_keyword = ""
        for step in tc.get("steps", []) or []:
            action = step.get("action") or ""
            target = step.get("target_element") or ""
            input_data = step.get("input_data") or ""
            expected = step.get("expected_output") or ""
            scene_id = step.get("evidence_scene_id") or ""
            ctrl_id = step.get("evidence_control_id") or ""
            edge_id = step.get("evidence_edge_id") or ""
            conf = step.get("proof_confidence", 0.0) or 0.0

            keyword = _classify_step(action)
            if keyword == prev_keyword:
                keyword = "And"
            prev_keyword = _classify_step(action)  # remember the real keyword

            step_text = _format_step_text(action, target, input_data)
            lines.append(f"    {keyword} {step_text}")
            if expected:
                lines.append(f"    Then I see \"{expected[:200]}\"")

            # Evidence trace as a comment so reviewers can verify against the demo
            ev_parts = []
            if scene_id:
                ev_parts.append(f"scene={scene_id[:8]}")
            if ctrl_id:
                ev_parts.append(f"control={ctrl_id[:8]}")
            if edge_id:
                ev_parts.append(f"edge={edge_id[:8]}")
            if conf:
                ev_parts.append(f"confidence={conf:.2f}")
            if ev_parts:
                lines.append(f"    # Evidence: {', '.join(ev_parts)}")

        if proven is not None and total is not None:
            lines.append(f"  # {proven}/{total} steps grounded in scene + control")
        lines.append("")

    return "\n".join(lines)


class GherkinExporter(TestExporter):
    format_id = "gherkin"
    label = "Gherkin (.feature)"
    file_extension = "feature"

    def render(self) -> ExportBundle:
        buf = io.BytesIO()
        with zipfile.ZipFile(buf, "w", zipfile.ZIP_DEFLATED) as zf:
            for inst_id, tcs in self.ctx.tc_by_inst.items():
                app_name = self.ctx.inst_name_map.get(inst_id, inst_id) or "App"
                content = _build_feature(app_name, tcs)
                zf.writestr(f"{safe_name(app_name)}.feature", content)
        buf.seek(0)
        return ExportBundle(
            payload=buf.getvalue(),
            content_type="application/zip",
            filename=f"gherkin-{self.ctx.artifact_id[:8]}.zip",
        )
