"""Gherkin (.feature) exporter (P5).

Emits one ``<app>.feature`` per app_instance, packaged in a ZIP. Plain-English
BDD-style scenarios derived from the visual evidence graph — perfect for
business stakeholder review and BDD teams (Cucumber, SpecFlow, Behave).

Each scenario step is rendered as Given / When / Then, with evidence
citation comments (``# Evidence: scene_id=...``) for traceability.
"""
from __future__ import annotations

import io
import zipfile

from .base import ExportBundle, TestExporter, safe_name


def _classify_step(action: str) -> str:
    """Pick Given/When/Then based on action verb."""
    a = (action or "").lower()
    if any(kw in a for kw in ("open", "navigate", "load", "visit", "go to", "is on")):
        return "Given"
    if any(kw in a for kw in (
        "click", "fill", "type", "enter", "input", "select",
        "choose", "submit", "press", "toggle", "drag", "upload",
    )):
        return "When"
    if any(kw in a for kw in (
        "verify", "assert", "check", "expect", "should",
        "see", "observe", "appears", "displayed",
    )):
        return "Then"
    return "And"


def _format_step_text(action: str, target: str, input_data: str) -> str:
    """Compose a human-readable step phrase from action + target + input."""
    parts = [(action or "").strip()]
    if target and target.strip().lower() not in (action or "").lower():
        parts.append(f'"{target.strip()}"')
    if input_data and input_data.strip():
        parts.append(f'with value "{input_data.strip()}"')
    return " ".join(p for p in parts if p)


def _build_feature(
    app_name: str, test_cases: list[dict],
) -> str:
    lines = [
        f"# App: {app_name}",
        "# Generated by Nexus QA Visual Evidence Pipeline (visual_strict).",
        "# Every step cites a specific scene + control from the recorded demo.",
        "",
        f"Feature: {app_name}",
        "",
    ]

    for tc in test_cases:
        title = tc.get("title") or "Unnamed scenario"
        strategy = tc.get("strategy") or "happy_path"
        proven = tc.get("visual_proven_steps")
        total = tc.get("visual_total_steps")

        tag = "@" + strategy.replace("_", "-")
        lines.append(f"  {tag}")
        lines.append(f"  Scenario: {title}")

        # Background-ish prefix: preconditions as Given lines
        for pre in tc.get("preconditions", []) or []:
            lines.append(f"    Given {pre}")

        prev_keyword = ""
        for step in tc.get("steps", []) or []:
            action = step.get("action") or ""
            target = step.get("target_element") or ""
            input_data = step.get("input_data") or ""
            expected = step.get("expected_output") or ""
            scene_id = step.get("evidence_scene_id") or ""
            ctrl_id = step.get("evidence_control_id") or ""
            edge_id = step.get("evidence_edge_id") or ""
            conf = step.get("proof_confidence", 0.0) or 0.0

            keyword = _classify_step(action)
            if keyword == prev_keyword:
                keyword = "And"
            prev_keyword = _classify_step(action)  # remember the real keyword

            step_text = _format_step_text(action, target, input_data)
            lines.append(f"    {keyword} {step_text}")
            if expected:
                lines.append(f"    Then I see \"{expected[:200]}\"")

            # Evidence trace as a comment so reviewers can verify against the demo
            ev_parts = []
            if scene_id:
                ev_parts.append(f"scene={scene_id[:8]}")
            if ctrl_id:
                ev_parts.append(f"control={ctrl_id[:8]}")
            if edge_id:
                ev_parts.append(f"edge={edge_id[:8]}")
            if conf:
                ev_parts.append(f"confidence={conf:.2f}")
            if ev_parts:
                lines.append(f"    # Evidence: {', '.join(ev_parts)}")

        if proven is not None and total is not None:
            lines.append(f"  # {proven}/{total} steps grounded in scene + control")
        lines.append("")

    return "\n".join(lines)


def _build_url_coverage_feature(
    page_visits: list[dict],
    page_actions: dict[str, list[dict]],
    form_snapshots: dict[str, dict],
) -> str:
    """Emit a Gherkin .feature walking the URL log + asserting form state.

    One Scenario per distinct URL visited.  The captured action sequence
    becomes the When/And steps; the form snapshot becomes the Then
    assertions.  Reads cleanly for business stakeholders who want to
    audit "what page did the user really go through".
    """
    if not page_visits:
        return ""

    lines: list[str] = [
        "# URL Coverage — generated from Phase 2 page_visits + form_snapshots.",
        "# One scenario per distinct URL the user visited.  Independent of the",
        "# canonical scene-keyed flow so merged-scene URLs still surface here.",
        "",
        "Feature: URL Coverage",
        "",
    ]

    for visit in page_visits:
        location = (visit.get("location") or "").strip()
        if not location:
            continue
        seq = visit.get("sequence_index")
        visit_id = visit.get("page_visit_id") or ""
        snapshot = form_snapshots.get(visit_id) or {}
        intent = (snapshot.get("page_intent") or "").strip()

        title_parts = [
            f"#{seq:02d}" if isinstance(seq, int) else f"#{seq}",
            intent,
            location,
        ]
        title = " — ".join(p for p in title_parts if p)

        lines.append("  @url-coverage")
        lines.append(f"  Scenario: {title}")
        if location.startswith("http://") or location.startswith("https://"):
            lines.append(f"    Given I open \"{location}\"")
        else:
            lines.append(f"    Given I open the page \"{location}\"")

        # Replay captured actions as When/And.
        actions = page_actions.get(visit_id) or []
        first_when = True
        for action in actions:
            verb = (action.get("verb") or "").lower()
            target = (action.get("target_label") or "").strip()
            value = action.get("value")
            keyword = "When" if first_when else "And"
            if verb == "type" and value:
                lines.append(f"    {keyword} I type \"{value}\" into \"{target}\"")
            elif verb == "select" and value:
                lines.append(f"    {keyword} I select \"{value}\" from \"{target}\"")
            elif verb == "click":
                lines.append(f"    {keyword} I click \"{target}\"")
            elif verb == "submit":
                lines.append(f"    {keyword} I submit \"{target}\"")
            elif verb == "navigate":
                lines.append(f"    {keyword} I navigate via \"{target}\"")
            elif verb == "hover":
                lines.append(f"    {keyword} I hover over \"{target}\"")
            elif verb == "none":
                continue  # placeholder rows skipped in narrative
            else:
                lines.append(f"    {keyword} I {verb} \"{target}\"")
            first_when = False

        # Form snapshot → Then assertions.
        fields: dict[str, str] = snapshot.get("fields") or {}
        first_then = True
        for label, value in fields.items():
            if not label:
                continue
            keyword = "Then" if first_then else "And"
            value_str = str(value or "")
            if value_str:
                lines.append(
                    f"    {keyword} the \"{label}\" field shows \"{value_str}\""
                )
            else:
                lines.append(f"    {keyword} the \"{label}\" field is present")
            first_then = False

        # Evidence footer.
        confidence = snapshot.get("overall_confidence")
        if confidence:
            lines.append(
                f"    # Snapshot confidence: {float(confidence):.2f}"
            )
        lines.append("")

    return "\n".join(lines)


class GherkinExporter(TestExporter):
    format_id = "gherkin"
    label = "Gherkin (.feature)"
    file_extension = "feature"

    def render(self) -> ExportBundle:
        buf = io.BytesIO()
        with zipfile.ZipFile(buf, "w", zipfile.ZIP_DEFLATED) as zf:
            for inst_id, tcs in self.ctx.tc_by_inst.items():
                app_name = self.ctx.inst_name_map.get(inst_id, inst_id) or "App"
                content = _build_feature(app_name, tcs)
                zf.writestr(f"{safe_name(app_name)}.feature", content)
            # Phase 2 — URL coverage feature, when extractor data is available.
            coverage = _build_url_coverage_feature(
                self.ctx.page_visits,
                self.ctx.page_actions,
                self.ctx.form_snapshots,
            )
            if coverage:
                zf.writestr("url-coverage.feature", coverage)
        buf.seek(0)
        return ExportBundle(
            payload=buf.getvalue(),
            content_type="application/zip",
            filename=f"gherkin-{self.ctx.artifact_id[:8]}.zip",
        )
