"""Playwright exporter (P5).

Emits one .spec.ts per app_instance, packaged in a ZIP. Every step's
selector + assertion is derived from EvidenceControl.playwright_selector
+ OCR. Steps that fail the 5-gate readiness check are emitted as
``test.skip(true, "UNPROVEN: <reason>")`` so the file still parses and
runs the proven subset.
"""
from __future__ import annotations

import io
import json
import zipfile

from .base import ExportBundle, ExportContext, TestExporter, safe_name
from .preparation import ACTIONABLE_STEP_TYPES, PROOF_CONFIDENCE_THRESHOLD


def _build_spec_ts(
    app_name: str, test_cases: list[dict], controls_by_id: dict[str, dict],
) -> str:
    total = sum(len(tc.get("steps", [])) for tc in test_cases)
    proven = sum(
        1 for tc in test_cases
        for step in tc.get("steps", [])
        if step.get("evidence_scene_id")
        and step.get("proof_confidence", 0) >= PROOF_CONFIDENCE_THRESHOLD
    )

    lines = [
        "import { test, expect } from '@playwright/test';",
        "",
        f"// App: {app_name}",
        f"// {proven} of {total} steps automation-ready. "
        f"{total - proven} unproven steps marked skip.",
        "// Generated by Nexus QA Visual Evidence Pipeline (visual_strict).",
        "",
    ]

    for tc in test_cases:
        tc_title = tc.get("title") or "Unnamed test"
        scenario_id = tc.get("scenario_id") or ""
        # P6: embed scenario_id in the test name so the CI ingest webhook
        # can re-correlate run results to scenarios.
        test_name = f"{scenario_id} — {tc_title}" if scenario_id else tc_title
        lines.append(f"test.describe({json.dumps(test_name)}, () => {{")
        lines.append(f"  test({json.dumps(test_name)}, async ({{ page }}) => {{")

        for step in tc.get("steps", []):
            action = step.get("action") or ""
            selector = step.get("target_element") or ""
            expected = step.get("expected_output") or ""
            scene_id = step.get("evidence_scene_id") or ""
            ctrl_id = step.get("evidence_control_id") or ""
            edge_id = step.get("evidence_edge_id") or ""
            conf = step.get("proof_confidence", 0.0) or 0.0
            action_lower = action.lower()

            is_actionable = any(kw in action_lower for kw in ACTIONABLE_STEP_TYPES)
            ctrl = controls_by_id.get(ctrl_id)
            passes_gate = (
                is_actionable
                and scene_id
                and ctrl_id
                and conf >= PROOF_CONFIDENCE_THRESHOLD
                and ctrl
                and ctrl.get("automation_ready")
                and expected
            )

            evidence_comment = (
                f"// Evidence: scene_id={scene_id[:8] if scene_id else 'none'}, "
                f"edge_id={edge_id[:8] if edge_id else 'none'}, "
                f"confidence={conf:.2f}, "
                f"selector_source={ctrl.get('selector_source', 'unknown') if ctrl else 'none'}"
            )

            if is_actionable and not passes_gate:
                if not scene_id:
                    reason = "no evidence_scene_id"
                elif not ctrl_id:
                    reason = "no evidence_control_id"
                elif conf < PROOF_CONFIDENCE_THRESHOLD:
                    reason = f"proof_confidence={conf:.2f} below threshold"
                elif not ctrl or not ctrl.get("automation_ready"):
                    reason = "selector not OCR-backed"
                elif not expected:
                    reason = "no expected_output"
                else:
                    reason = "gate check failed"
                lines.append(f"    {evidence_comment}")
                lines.append(
                    f"    test.skip(true, {json.dumps('UNPROVEN: ' + reason)});"
                )
                continue

            lines.append(f"    {evidence_comment}")
            lines.append(f"    await test.step({json.dumps(action)}, async () => {{")
            if selector:
                if any(kw in action_lower for kw in ("fill", "type", "enter", "input")):
                    input_value = step.get("input_data") or ""
                    lines.append(
                        f"      await page.locator({json.dumps(selector)}).fill({json.dumps(input_value)});"
                    )
                elif any(kw in action_lower for kw in ("select", "choose")):
                    selected = step.get("input_data") or ""
                    lines.append(
                        f"      await page.locator({json.dumps(selector)}).selectOption({json.dumps(selected)});"
                    )
                elif any(kw in action_lower for kw in ("verify", "assert", "check", "expect", "should")):
                    lines.append(
                        f"      await expect(page.locator({json.dumps(selector)})).toBeVisible();"
                    )
                else:
                    lines.append(
                        f"      await page.locator({json.dumps(selector)}).click();"
                    )
            else:
                lines.append(f"      // TODO: automate — {action}")
            if expected:
                lines.append(
                    f"      await expect(page.getByText({json.dumps(expected[:120])})).toBeVisible();"
                )
            lines.append("    });")

        lines.append("  });")
        lines.append("});")
        lines.append("")

    return "\n".join(lines)


def _build_url_coverage_spec(
    page_visits: list[dict],
    page_actions: dict[str, list[dict]],
    form_snapshots: dict[str, dict],
) -> str:
    """Emit a Playwright spec that walks the URL log and asserts each page's
    final form snapshot.

    Generated only when the Phase 2 page_visit / form_snapshot extractors
    have produced data.  Complementary to the per-app test specs — gives
    QA engineers an explicit URL-by-URL view of the workflow that
    survives the scene_grouper merging multiple distinct URLs into one
    scene.

    Each visited URL becomes one test that:
      1. Navigates to the URL.
      2. For every captured form field, asserts the value (or selector
         existence when no value was visible).
    """
    if not page_visits:
        return ""

    lines: list[str] = [
        "import { test, expect } from '@playwright/test';",
        "",
        "// URL Coverage — generated from Phase 2 page_visits + form_snapshots.",
        "// One test per distinct URL the user visited.  Use this to spot-",
        "// check page-level state independent of the scene-keyed action flow.",
        "",
    ]

    for visit in page_visits:
        location = (visit.get("location") or "").strip()
        if not location:
            continue
        seq = visit.get("sequence_index")
        visit_id = visit.get("page_visit_id") or ""
        snapshot = form_snapshots.get(visit_id) or {}
        intent = (snapshot.get("page_intent") or "").strip()

        title_parts = [f"#{seq:02d}" if isinstance(seq, int) else f"#{seq}"]
        if intent:
            title_parts.append(intent)
        title_parts.append(location)
        test_title = " — ".join(p for p in title_parts if p)

        lines.append(f"test({json.dumps(test_title)}, async ({{ page }}) => {{")
        if location.startswith("http://") or location.startswith("https://"):
            lines.append(f"  await page.goto({json.dumps(location)});")
        else:
            lines.append(f"  // Native UI page — automation runner must open: {location}")

        fields: dict[str, str] = (snapshot.get("fields") or {})
        field_kinds: dict[str, str] = (snapshot.get("field_kinds") or {})
        if fields:
            lines.append("  // Final form snapshot for this page:")
            for label, value in fields.items():
                if not label:
                    continue
                kind = (field_kinds.get(label) or "other").lower()
                value_str = str(value or "")
                if kind in ("checkbox", "radio"):
                    if value_str.lower() in ("true", "on", "yes", "checked"):
                        lines.append(
                            f"  await expect(page.getByLabel({json.dumps(label)})).toBeChecked();"
                        )
                    else:
                        lines.append(
                            f"  await expect(page.getByLabel({json.dumps(label)})).not.toBeChecked();"
                        )
                elif kind in ("dropdown", "text_field"):
                    if value_str:
                        lines.append(
                            f"  await expect(page.getByLabel({json.dumps(label)})).toHaveValue({json.dumps(value_str)});"
                        )
                    else:
                        lines.append(
                            f"  await expect(page.getByLabel({json.dumps(label)})).toBeVisible();"
                        )
                else:
                    if value_str:
                        lines.append(
                            f"  await expect(page.getByText({json.dumps(value_str[:120])})).toBeVisible();"
                        )
                    else:
                        lines.append(
                            f"  await expect(page.getByText({json.dumps(label[:120])})).toBeVisible();"
                        )

        actions = page_actions.get(visit_id) or []
        if actions:
            lines.append("  // Captured actions on this page (for reference):")
            for action in actions:
                verb = (action.get("verb") or "").lower()
                target = (action.get("target_label") or "")[:120]
                value = action.get("value")
                value_repr = json.dumps(value) if value is not None else "null"
                lines.append(
                    f"  // - {verb}: target={json.dumps(target)} value={value_repr}"
                )

        lines.append("});")
        lines.append("")

    return "\n".join(lines)


class PlaywrightExporter(TestExporter):
    format_id = "playwright"
    label = "Playwright (.spec.ts)"
    file_extension = "spec.ts"

    def render(self) -> ExportBundle:
        buf = io.BytesIO()
        with zipfile.ZipFile(buf, "w", zipfile.ZIP_DEFLATED) as zf:
            for inst_id, tcs in self.ctx.tc_by_inst.items():
                app_name = self.ctx.inst_name_map.get(inst_id, inst_id) or "App"
                spec = _build_spec_ts(app_name, tcs, self.ctx.controls_by_id)
                zf.writestr(f"{safe_name(app_name)}.spec.ts", spec)
            # Phase 2 — emit the URL-coverage spec when extractor data
            # is available.  Goes into a separate file so existing
            # downstream Playwright configs that look for ``*.spec.ts``
            # pick it up automatically without changes.
            coverage = _build_url_coverage_spec(
                self.ctx.page_visits,
                self.ctx.page_actions,
                self.ctx.form_snapshots,
            )
            if coverage:
                zf.writestr("url-coverage.spec.ts", coverage)
        buf.seek(0)
        return ExportBundle(
            payload=buf.getvalue(),
            content_type="application/zip",
            filename=f"playwright-{self.ctx.artifact_id[:8]}.zip",
        )
