"""Playwright exporter (P5).

Emits one .spec.ts per app_instance, packaged in a ZIP. Every step's
selector + assertion is derived from EvidenceControl.playwright_selector
+ OCR. Steps that fail the 5-gate readiness check are emitted as
``test.skip(true, "UNPROVEN: <reason>")`` so the file still parses and
runs the proven subset.
"""
from __future__ import annotations

import io
import json
import zipfile

from .base import ExportBundle, ExportContext, TestExporter, safe_name
from .preparation import ACTIONABLE_STEP_TYPES, PROOF_CONFIDENCE_THRESHOLD


def _build_spec_ts(
    app_name: str, test_cases: list[dict], controls_by_id: dict[str, dict],
) -> str:
    total = sum(len(tc.get("steps", [])) for tc in test_cases)
    proven = sum(
        1 for tc in test_cases
        for step in tc.get("steps", [])
        if step.get("evidence_scene_id")
        and step.get("proof_confidence", 0) >= PROOF_CONFIDENCE_THRESHOLD
    )

    lines = [
        "import { test, expect } from '@playwright/test';",
        "",
        f"// App: {app_name}",
        f"// {proven} of {total} steps automation-ready. "
        f"{total - proven} unproven steps marked skip.",
        "// Generated by Nexus QA Visual Evidence Pipeline (visual_strict).",
        "",
    ]

    for tc in test_cases:
        tc_title = tc.get("title") or "Unnamed test"
        scenario_id = tc.get("scenario_id") or ""
        # P6: embed scenario_id in the test name so the CI ingest webhook
        # can re-correlate run results to scenarios.
        test_name = f"{scenario_id} — {tc_title}" if scenario_id else tc_title
        lines.append(f"test.describe({json.dumps(test_name)}, () => {{")
        lines.append(f"  test({json.dumps(test_name)}, async ({{ page }}) => {{")

        for step in tc.get("steps", []):
            action = step.get("action") or ""
            selector = step.get("target_element") or ""
            expected = step.get("expected_output") or ""
            scene_id = step.get("evidence_scene_id") or ""
            ctrl_id = step.get("evidence_control_id") or ""
            edge_id = step.get("evidence_edge_id") or ""
            conf = step.get("proof_confidence", 0.0) or 0.0
            action_lower = action.lower()

            is_actionable = any(kw in action_lower for kw in ACTIONABLE_STEP_TYPES)
            ctrl = controls_by_id.get(ctrl_id)
            passes_gate = (
                is_actionable
                and scene_id
                and ctrl_id
                and conf >= PROOF_CONFIDENCE_THRESHOLD
                and ctrl
                and ctrl.get("automation_ready")
                and expected
            )

            evidence_comment = (
                f"// Evidence: scene_id={scene_id[:8] if scene_id else 'none'}, "
                f"edge_id={edge_id[:8] if edge_id else 'none'}, "
                f"confidence={conf:.2f}, "
                f"selector_source={ctrl.get('selector_source', 'unknown') if ctrl else 'none'}"
            )

            if is_actionable and not passes_gate:
                if not scene_id:
                    reason = "no evidence_scene_id"
                elif not ctrl_id:
                    reason = "no evidence_control_id"
                elif conf < PROOF_CONFIDENCE_THRESHOLD:
                    reason = f"proof_confidence={conf:.2f} below threshold"
                elif not ctrl or not ctrl.get("automation_ready"):
                    reason = "selector not OCR-backed"
                elif not expected:
                    reason = "no expected_output"
                else:
                    reason = "gate check failed"
                lines.append(f"    {evidence_comment}")
                lines.append(
                    f"    test.skip(true, {json.dumps('UNPROVEN: ' + reason)});"
                )
                continue

            lines.append(f"    {evidence_comment}")
            lines.append(f"    await test.step({json.dumps(action)}, async () => {{")
            if selector:
                if any(kw in action_lower for kw in ("fill", "type", "enter", "input")):
                    input_value = step.get("input_data") or ""
                    lines.append(
                        f"      await page.locator({json.dumps(selector)}).fill({json.dumps(input_value)});"
                    )
                elif any(kw in action_lower for kw in ("select", "choose")):
                    selected = step.get("input_data") or ""
                    lines.append(
                        f"      await page.locator({json.dumps(selector)}).selectOption({json.dumps(selected)});"
                    )
                elif any(kw in action_lower for kw in ("verify", "assert", "check", "expect", "should")):
                    lines.append(
                        f"      await expect(page.locator({json.dumps(selector)})).toBeVisible();"
                    )
                else:
                    lines.append(
                        f"      await page.locator({json.dumps(selector)}).click();"
                    )
            else:
                lines.append(f"      // TODO: automate — {action}")
            if expected:
                lines.append(
                    f"      await expect(page.getByText({json.dumps(expected[:120])})).toBeVisible();"
                )
            lines.append("    });")

        lines.append("  });")
        lines.append("});")
        lines.append("")

    return "\n".join(lines)


class PlaywrightExporter(TestExporter):
    format_id = "playwright"
    label = "Playwright (.spec.ts)"
    file_extension = "spec.ts"

    def render(self) -> ExportBundle:
        buf = io.BytesIO()
        with zipfile.ZipFile(buf, "w", zipfile.ZIP_DEFLATED) as zf:
            for inst_id, tcs in self.ctx.tc_by_inst.items():
                app_name = self.ctx.inst_name_map.get(inst_id, inst_id) or "App"
                spec = _build_spec_ts(app_name, tcs, self.ctx.controls_by_id)
                zf.writestr(f"{safe_name(app_name)}.spec.ts", spec)
        buf.seek(0)
        return ExportBundle(
            payload=buf.getvalue(),
            content_type="application/zip",
            filename=f"playwright-{self.ctx.artifact_id[:8]}.zip",
        )
